In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("/Users/jenniferkosmatka/MIT Dropbox/Jennifer Kosmatka/pssm_lc3b_lir-adjacent/data/raw/231209_completedata_JK.csv", sep="\t")

In [4]:
df

,Unnamed: 0,ID,ER 0,ER 1,ER 3,ER 4,ER 5,ER 6,Input Count,1 Count,...,Query start,Query End,Hit Start,Hit End,E-value,Score (Bits),z_score_4,z_score_5,z_score_6,avg_z_score
0,0,DIDNFDIDDFDDDDDWEDICII,0,4.094998,9.506665,12.105609,13.229315,14.031836,976,9092,...,5.0,19.0,256.0,270.0,1.900000e+00,23.1,3.574377,4.082822,4.670163,4.11
1,1,LWQPHSSKQDDMWEHIAISML,0,4.420856,9.955033,12.104137,12.854852,13.584948,244,2849,...,1.0,17.0,465.0,481.0,4.550000e-07,42.0,3.573749,3.927170,4.482965,3.99
2,2,VIEEADLDGDGSWALLTSRT,0,6.061220,10.521183,11.960512,12.786388,12.782009,10,364,...,1.0,11.0,152.0,162.0,7.100000e-02,27.3,3.512489,3.898712,4.146620,3.85
3,3,LHNPESGEEAVALLEELQRDLGWDILA,0,5.191722,10.334677,12.020974,12.594453,12.509488,13,259,...,1.0,21.0,117.0,137.0,1.010000e-08,47.0,3.538278,3.818930,4.032463,3.80
4,4,QIPENSTSSQADDEWCYVLI,0,5.148098,10.131437,11.838327,12.629829,12.705135,91,1759,...,1.0,10.0,552.0,561.0,1.400000e+00,23.5,3.460374,3.833635,4.114419,3.80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
966443,968944,YWKLTIMSFIKLMVVNPSILIVSFMVMKLPKMCMK,0,NaN,NaN,NaN,NaN,NaN,9,0,...,6.0,35.0,279.0,308.0,8.800000e+00,22.3,NaN,NaN,NaN,NaN
966444,968945,YWKNLPVCKPCPAASFLLCTEY,0,NaN,NaN,NaN,NaN,NaN,1,0,...,6.0,16.0,445.0,455.0,6.300000e+00,21.9,NaN,NaN,NaN,NaN
966445,968946,YWKYGEAASTECNSVCFGDHTQPCGGDGRIILFDTL,0,NaN,NaN,NaN,NaN,NaN,34,0,...,1.0,36.0,175.0,210.0,8.050000e-21,81.6,NaN,NaN,NaN,NaN
966446,968947,YWKYGEAASTACNSVCFGGSHPTVWWRWPYHPL,0,NaN,NaN,NaN,NaN,NaN,11,0,...,1.0,18.0,175.0,192.0,4.000000e-06,40.0,NaN,NaN,NaN,NaN
966447,968948,YWKYGEAAVPNATASASGITPNRVVAMAVSSSLIL,0,NaN,NaN,NaN,NaN,NaN,1,0,...,4.0,35.0,657.0,688.0,1.900000e-01,26.9,NaN,NaN,NaN,NaN

In [5]:
df = df[df['Input Count'] >=10]

In [6]:
df

,Unnamed: 0,ID,ER 0,ER 1,ER 3,ER 4,ER 5,ER 6,Input Count,1 Count,...,Query start,Query End,Hit Start,Hit End,E-value,Score (Bits),z_score_4,z_score_5,z_score_6,avg_z_score
0,0,DIDNFDIDDFDDDDDWEDICII,0,4.094998,9.506665,12.105609,13.229315,14.031836,976,9092,...,5.0,19.0,256.0,270.0,1.900000e+00,23.1,3.574377,4.082822,4.670163,4.11
1,1,LWQPHSSKQDDMWEHIAISML,0,4.420856,9.955033,12.104137,12.854852,13.584948,244,2849,...,1.0,17.0,465.0,481.0,4.550000e-07,42.0,3.573749,3.927170,4.482965,3.99
2,2,VIEEADLDGDGSWALLTSRT,0,6.061220,10.521183,11.960512,12.786388,12.782009,10,364,...,1.0,11.0,152.0,162.0,7.100000e-02,27.3,3.512489,3.898712,4.146620,3.85
3,3,LHNPESGEEAVALLEELQRDLGWDILA,0,5.191722,10.334677,12.020974,12.594453,12.509488,13,259,...,1.0,21.0,117.0,137.0,1.010000e-08,47.0,3.538278,3.818930,4.032463,3.80
4,4,QIPENSTSSQADDEWCYVLI,0,5.148098,10.131437,11.838327,12.629829,12.705135,91,1759,...,1.0,10.0,552.0,561.0,1.400000e+00,23.5,3.460374,3.833635,4.114419,3.80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
966434,968935,YWITIDNPYVVAWHGYATGRLAPGIRGSPRLGYLVA,0,3.249749,NaN,NaN,NaN,NaN,27,140,...,1.0,36.0,233.0,268.0,1.710000e-19,78.2,NaN,NaN,NaN,NaN
966438,968939,YWKESDKLLLIGLPAEEVPLPRLRNMIENVIQTLKF,0,2.764096,1.467049,-0.573207,NaN,NaN,64,237,...,1.0,36.0,378.0,413.0,3.010000e-19,77.4,NaN,NaN,NaN,NaN
966439,968940,YWKNESGTWIQYGEEKDKRKNSNVDSSYLESLYQSC,0,0.565013,NaN,NaN,NaN,NaN,31,25,...,1.0,36.0,610.0,645.0,8.820000e-20,79.0,NaN,NaN,NaN,NaN
966445,968946,YWKYGEAASTECNSVCFGDHTQPCGGDGRIILFDTL,0,NaN,NaN,NaN,NaN,NaN,34,0,...,1.0,36.0,175.0,210.0,8.050000e-21,81.6,NaN,NaN,NaN,NaN
966446,968947,YWKYGEAASTACNSVCFGGSHPTVWWRWPYHPL,0,NaN,NaN,NaN,NaN,NaN,11,0,...,1.0,18.0,175.0,192.0,4.000000e-06,40.0,NaN,NaN,NaN,NaN

In [7]:
df = df[df['avg_z_score']>=1.70]

In [8]:
df

,Unnamed: 0,ID,ER 0,ER 1,ER 3,ER 4,ER 5,ER 6,Input Count,1 Count,...,Query start,Query End,Hit Start,Hit End,E-value,Score (Bits),z_score_4,z_score_5,z_score_6,avg_z_score
0,0,DIDNFDIDDFDDDDDWEDICII,0,4.094998,9.506665,12.105609,13.229315,14.031836,976,9092,...,5.0,19.0,256.0,270.0,1.900000e+00,23.1,3.574377,4.082822,4.670163,4.11
1,1,LWQPHSSKQDDMWEHIAISML,0,4.420856,9.955033,12.104137,12.854852,13.584948,244,2849,...,1.0,17.0,465.0,481.0,4.550000e-07,42.0,3.573749,3.927170,4.482965,3.99
2,2,VIEEADLDGDGSWALLTSRT,0,6.061220,10.521183,11.960512,12.786388,12.782009,10,364,...,1.0,11.0,152.0,162.0,7.100000e-02,27.3,3.512489,3.898712,4.146620,3.85
3,3,LHNPESGEEAVALLEELQRDLGWDILA,0,5.191722,10.334677,12.020974,12.594453,12.509488,13,259,...,1.0,21.0,117.0,137.0,1.010000e-08,47.0,3.538278,3.818930,4.032463,3.80
4,4,QIPENSTSSQADDEWCYVLI,0,5.148098,10.131437,11.838327,12.629829,12.705135,91,1759,...,1.0,10.0,552.0,561.0,1.400000e+00,23.5,3.460374,3.833635,4.114419,3.80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
415,422,ASQGSDDDWDDEWDDSSTVADEPGALGSGAYPDLDG,0,6.093138,7.077381,7.625063,7.758434,6.743610,28,1042,...,1.0,36.0,146.0,181.0,1.450000e-17,72.4,1.663313,1.808750,1.617183,1.70
416,423,LEATGPGGSQAINNLRRSNSTTQVSQPRSGSPRPTE,0,6.929649,7.823032,8.205766,7.752720,6.165534,11,731,...,1.0,36.0,59.0,94.0,3.150000e-18,74.3,1.910997,1.806375,1.375032,1.70
417,424,MPNTSVVLDTDAEFVILLLFLLLLFFFFRASFA,0,4.431676,7.914457,8.140802,7.387363,6.622837,407,4788,...,1.0,15.0,642.0,656.0,1.750000e-04,35.4,1.883288,1.654507,1.566592,1.70
418,425,MSQAVQQRYSTIKQNMGTQFI,0,3.409332,7.021036,7.790198,7.932998,6.418514,48,278,...,NaN,NaN,NaN,NaN,NaN,NaN,1.733747,1.881311,1.481003,1.70
419,426,RVVNGAFMVLKGHRSIVNQARFNPHTYMICSLV,0,5.037973,6.692744,7.307211,7.830723,7.013530,11,197,...,1.0,31.0,320.0,350.0,4.730000e-17,70.9,1.527741,1.838798,1.730251,1.70

In [18]:
# This means: 1 amino acid from F/W/Y, followed by any 3, then 1 from L/V/I
pattern = r'[FWY]..[LVIFWY]'

# Filter rows where 'ID' matches the motif
matching_df = df[df['ID'].str.contains(pattern, regex=True)]

In [19]:
matching_df

,Unnamed: 0,ID,ER 0,ER 1,ER 3,ER 4,ER 5,ER 6,Input Count,1 Count,...,Query start,Query End,Hit Start,Hit End,E-value,Score (Bits),z_score_4,z_score_5,z_score_6,avg_z_score
0,0,DIDNFDIDDFDDDDDWEDICII,0,4.094998,9.506665,12.105609,13.229315,14.031836,976,9092,...,5.0,19.0,256.0,270.0,1.900000e+00,23.1,3.574377,4.082822,4.670163,4.11
1,1,LWQPHSSKQDDMWEHIAISML,0,4.420856,9.955033,12.104137,12.854852,13.584948,244,2849,...,1.0,17.0,465.0,481.0,4.550000e-07,42.0,3.573749,3.927170,4.482965,3.99
2,2,VIEEADLDGDGSWALLTSRT,0,6.061220,10.521183,11.960512,12.786388,12.782009,10,364,...,1.0,11.0,152.0,162.0,7.100000e-02,27.3,3.512489,3.898712,4.146620,3.85
3,3,LHNPESGEEAVALLEELQRDLGWDILA,0,5.191722,10.334677,12.020974,12.594453,12.509488,13,259,...,1.0,21.0,117.0,137.0,1.010000e-08,47.0,3.538278,3.818930,4.032463,3.80
4,4,QIPENSTSSQADDEWCYVLI,0,5.148098,10.131437,11.838327,12.629829,12.705135,91,1759,...,1.0,10.0,552.0,561.0,1.400000e+00,23.5,3.460374,3.833635,4.114419,3.80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
413,420,HLAAGYNNLEVAEYLLEHGADVNAQTRVV,0,4.039740,7.065926,7.296732,7.828102,7.030019,29,260,...,1.0,27.0,842.0,868.0,3.130000e-11,54.3,1.523272,1.837709,1.737157,1.70
415,422,ASQGSDDDWDDEWDDSSTVADEPGALGSGAYPDLDG,0,6.093138,7.077381,7.625063,7.758434,6.743610,28,1042,...,1.0,36.0,146.0,181.0,1.450000e-17,72.4,1.663313,1.808750,1.617183,1.70
417,424,MPNTSVVLDTDAEFVILLLFLLLLFFFFRASFA,0,4.431676,7.914457,8.140802,7.387363,6.622837,407,4788,...,1.0,15.0,642.0,656.0,1.750000e-04,35.4,1.883288,1.654507,1.566592,1.70
418,425,MSQAVQQRYSTIKQNMGTQFI,0,3.409332,7.021036,7.790198,7.932998,6.418514,48,278,...,NaN,NaN,NaN,NaN,NaN,NaN,1.733747,1.881311,1.481003,1.70
419,426,RVVNGAFMVLKGHRSIVNQARFNPHTYMICSLV,0,5.037973,6.692744,7.307211,7.830723,7.013530,11,197,...,1.0,31.0,320.0,350.0,4.730000e-17,70.9,1.527741,1.838798,1.730251,1.70

In [14]:
df_jh = pd.read_csv("/Users/jenniferkosmatka/Downloads/09_binders_from_Jackson.csv", sep=",")

In [48]:
df_jh.tail(50)

                                       ID  Input Count  avg_z_score     7mer
223  MVEDYLANSYQDSVTFDDVAVEFTPEEWALLDTTEK          142         1.83  SVTFDDV
224  MVEDYLANSYQDSVTFDDVAVEFTPEEWALLDTTEK          142         1.83  PEEWALL
225   AASFHSAVFSLLKANNPWPASTSCCVPTARRPLSL           19         1.83  SAVFSLL
226          TAVALAYGIYKQDLPPLDEKPRNVVFIV           20         1.83  ALAYGIY
227   LSAGGPLANPEVDTREWVVLGKGLSRSALFRSRVR           57         1.82  TREWVVL
228       LNRYAVEGRDLTLQYNIYNVGSSAALDVGTV           49         1.81  TLQYNIY
229                  LLIRGWNACPEVVRNFLKLS           11         1.81  VRNFLKL
230         VNLPRFWESHACLACDHVKRHQEYKLLVI           30         1.81  HQEYKLL
231                  SGAIVDLISRQYDKFLTHFI           25         1.81  SRQYDKF
232              ALSWNHFILSSGSRLGRVYHHDVG           14         1.80  ALSWNHF
233                KASPPFPLISNAQALAQEVQTF           13         1.79  SPPFPLI
234         INGTEWTRQLVMKKMVPTCMLQRFHKFLV           12         1.79  LQRFHKF
235  HLESLTLTGTKISSIPNNLCQEQKMLRTLDLSYNNV           10         1.79  DLSYNNV
236               LMPILVEKFPFVRKSERTGMLRS           35         1.79  VEKFPFV
237  EYEEENEEEDAEKWNEMDFEIIETNDTMRHSIIETS           40         1.79  EMDFEII
238                MTEYKLVVVGAGGVGKSALRFS           18         1.79  MTEYKLV
239   PNAGKSSLLRAISNARPAVASYPFTTLKPHVGIVH           18         1.78  SYPFTTL
240                  LTGLLTLGVNGHGQQNFHLY           21         1.77  QQNFHLY
241         IQGSLQDIFKFARTSPSHVKSVPLWYLRF           32         1.77  PLWYLRF
242              GMRALSLAKNNSLMPMSKAPFKSY           11         1.77  KAPFKSY
243            QAKAIFEKVKRFRMHVEQKDTFIVYI           10         1.77  KAIFEKV
244            QAKAIFEKVKRFRMHVEQKDTFIVYI           10         1.77  KDTFIVY
245          PLEQVADDGLYEFLDFVDATDRYRSLWV           41         1.77  TDRYRSL
246               MDLAKHLPHAFSKLETHGAFLSY           40         1.77  PHAFSKL
247               MDLAKHLPHAFSKLETHGAFLSY           40         1.77  HGAFLSY
248          PLEQVADDGLYEFLDFVDATDRYRSLWV           41         1.77  DGLYEFL
249                AVQYFWDRGHRDIMSFASVALQ           10         1.76  IMSFASV
250       IPSESKGFRAALSSNPSFWQIHSLVSQLKPH           12         1.76  NPSFWQI
251               MSNPFAHLAEPLDPVQPGKKFLI           22         1.76  SNPFAHL
252     KALGPLLAGTGVRPPNMSLDYDFLRNGASRNAA           11         1.76  SLDYDFL
253     ILKSDAAKPLLGHDAVIQALAQKVFMSLTRKNW           17         1.75  QKVFMSL
254    LTRYLNWIGVPTREFNVGQYRRDVVKTYKSFEFL           23         1.74  VKTYKSF
255    LTRYLNWIGVPTREFNVGQYRRDVVKTYKSFEFL           23         1.74  LTRYLNW
256          LSGPVTRLALSTSSRPLSALGLRFLSFK           16         1.73  GLRFLSF
257        FYNHKTSVFTPAYGSVTNVRINSTMTTPQV           18         1.73  TPAYGSV
258    EQLFYRIAHLNPVSSICCGWPPSPLPAGATAARR           14         1.72  EQLFYRI
259    SEDGPGDGFTILSSKSLVLGQKLSLTDISHIGST           45         1.72  GDGFTIL
260  SPVVERLGFDENFVDLTEMVEKRLQQLQSDELSAVT          182         1.72  DENFVDL
261                EVRFTNVPERTQIDVGRILYSV           18         1.71  EVRFTNV
262  GFWTGLGTGGILGYLFGSNRAATPFSDSWYYPSYPP           23         1.71  SWYYPSY
263     GKALSVPPTLFVTNVFTLVNVHMSAVNVGRPTA           10         1.71  TNVFTLV
264               HAHSQSAEAERPANTSPWQYLAL           27         1.71  TSPWQYL
265        MSALKVNKNNAKLWNNVGHALEMKRTLSVL           28         1.71  AKLWNNV
266                MARVPLTFSDVAIASLRRSGNI           19         1.71  PLTFSDV
267     MPNTSVVLDTDAEFVILLLFLLLLFFFFRASFA          407         1.70  DAEFVIL
268     MPNTSVVLDTDAEFVILLLFLLLLFFFFRASFA          407         1.70  LLLFFFF
269         HLAAGYNNLEVAEYLLEHGADVNAQTRVV           29         1.70  AAGYNNL
270  ASQGSDDDWDDEWDDSSTVADEPGALGSGAYPDLDG           28         1.70  SGAYPDL
271                 MSQAVQQRYSTIKQNMGTQFI           48         1.70  QQRYSTI
272     RVVNGAFMVLKGHRSIVNQARFNPHTYMICSLV           11         1.70  NGAFMVL

In [16]:
df_jk = pd.read_csv("/Users/jenniferkosmatka/Downloads/09_binders_from_Jen.csv", sep=",")

In [17]:
df_jk

                                    ID  Input Count  avg_z_score     7mer
0               DIDNFDIDDFDDDDDWEDICII          976         4.11  DDDWEDI
1                LWQPHSSKQDDMWEHIAISML          244         3.99  DDMWEHI
2                 VIEEADLDGDGSWALLTSRT           10         3.85  DGSWALL
3          LHNPESGEEAVALLEELQRDLGWDILA           13         3.80  DLGWDIL
4                 QIPENSTSSQADDEWCYVLI           91         3.80  DDEWCYV
..                                 ...          ...          ...      ...
292  MPNTSVVLDTDAEFVILLLFLLLLFFFFRASFA          407         1.70  LLLFLLL
293  MPNTSVVLDTDAEFVILLLFLLLLFFFFRASFA          407         1.70  LLLFFFF
294      HLAAGYNNLEVAEYLLEHGADVNAQTRVV           29         1.70  AAGYNNL
295  RVVNGAFMVLKGHRSIVNQARFNPHTYMICSLV           11         1.70  NGAFMVL
296              MSQAVQQRYSTIKQNMGTQFI           48         1.70  QQRYSTI

[297 rows x 4 columns]

In [20]:
# This means: 1 amino acid from F/W/Y, followed by any 3, then 1 from L/V/I
pattern = r'[FWY]..[LVIFWY]'

# Filter rows where 'ID' matches the motif
matching_df_jk = df_jk[df_jk['ID'].str.contains(pattern, regex=True)]

In [49]:
matching_df_jk.tail(10)

                                       ID  Input Count  avg_z_score     7mer
287        MSALKVNKNNAKLWNNVGHALEMKRTLSVL           28         1.71  AKLWNNV
288                MARVPLTFSDVAIASLRRSGNI           19         1.71  PLTFSDV
289  GFWTGLGTGGILGYLFGSNRAATPFSDSWYYPSYPP           23         1.71  SWYYPSY
290  GFWTGLGTGGILGYLFGSNRAATPFSDSWYYPSYPP           23         1.71  RGFWTGL
291     MPNTSVVLDTDAEFVILLLFLLLLFFFFRASFA          407         1.70  DAEFVIL
292     MPNTSVVLDTDAEFVILLLFLLLLFFFFRASFA          407         1.70  LLLFLLL
293     MPNTSVVLDTDAEFVILLLFLLLLFFFFRASFA          407         1.70  LLLFFFF
294         HLAAGYNNLEVAEYLLEHGADVNAQTRVV           29         1.70  AAGYNNL
295     RVVNGAFMVLKGHRSIVNQARFNPHTYMICSLV           11         1.70  NGAFMVL
296                 MSQAVQQRYSTIKQNMGTQFI           48         1.70  QQRYSTI

In [111]:
df_postprocess = pd.read_csv('/Users/jenniferkosmatka/MIT Dropbox/jhdavislab/06_davis_lab_papers/in_preparation/03_lc3bscreen_jk/supporting data/SF3_input_postcollapse_JK.csv')

In [112]:
df_postprocess

,Unnamed: 0,ID,ER 0_x,ER 1_x,ER 3_x,ER 4_x,ER 5_x,ER 6_x,Cluster Id_x,Input Count_x,...,Query start_x,Query End_x,Hit Start_x,Hit End_x,E-value_x,Score (Bits)_x,z_score_4,z_score_5,z_score_6,avg_z_score
0,229422,DIDNFDIDDFDDDDDWEDICII,0,4.094998,9.506665,12.105609,13.229315,14.031836,229609,976,...,5.0,19.0,256.0,270.0,1.900000e+00,23.1,3.574377,4.082822,4.670163,4.11
1,683178,LWQPHSSKQDDMWEHIAISML,0,4.420856,9.955033,12.104137,12.854852,13.584948,683868,244,...,1.0,17.0,465.0,481.0,4.550000e-07,42.0,3.573749,3.927170,4.482965,3.99
2,426137,VIEEADLDGDGSWALLTSRT,0,6.061220,10.521183,11.960512,12.786388,12.782009,426523,10,...,1.0,11.0,152.0,162.0,7.100000e-02,27.3,3.512489,3.898712,4.146620,3.85
3,480519,LHNPESGEEAVALLEELQRDLGWDILA,0,5.191722,10.334677,12.020974,12.594453,12.509488,480943,13,...,1.0,21.0,117.0,137.0,1.010000e-08,47.0,3.538278,3.818930,4.032463,3.80
4,810153,QIPENSTSSQADDEWCYVLI,0,5.148098,10.131437,11.838327,12.629829,12.705135,810989,91,...,1.0,10.0,552.0,561.0,1.400000e+00,23.5,3.460374,3.833635,4.114419,3.80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
968944,968944,YWKLTIMSFIKLMVVNPSILIVSFMVMKLPKMCMK,0,NaN,NaN,NaN,NaN,NaN,969981,9,...,6.0,35.0,279.0,308.0,8.800000e+00,22.3,NaN,NaN,NaN,NaN
968945,968945,YWKNLPVCKPCPAASFLLCTEY,0,NaN,NaN,NaN,NaN,NaN,969982,1,...,6.0,16.0,445.0,455.0,6.300000e+00,21.9,NaN,NaN,NaN,NaN
968946,968946,YWKYGEAASTECNSVCFGDHTQPCGGDGRIILFDTL,0,NaN,NaN,NaN,NaN,NaN,969983,34,...,1.0,36.0,175.0,210.0,8.050000e-21,81.6,NaN,NaN,NaN,NaN
968947,968947,YWKYGEAASTACNSVCFGGSHPTVWWRWPYHPL,0,NaN,NaN,NaN,NaN,NaN,969984,11,...,1.0,18.0,175.0,192.0,4.000000e-06,40.0,NaN,NaN,NaN,NaN
968948,968948,YWKYGEAAVPNATASASGITPNRVVAMAVSSSLIL,0,NaN,NaN,NaN,NaN,NaN,969985,1,...,4.0,35.0,657.0,688.0,1.900000e-01,26.9,NaN,NaN,NaN,NaN

In [113]:
df2 = df_postprocess[df_postprocess['Input Count_x']>=10]

In [114]:
df2

,Unnamed: 0,ID,ER 0_x,ER 1_x,ER 3_x,ER 4_x,ER 5_x,ER 6_x,Cluster Id_x,Input Count_x,...,Query start_x,Query End_x,Hit Start_x,Hit End_x,E-value_x,Score (Bits)_x,z_score_4,z_score_5,z_score_6,avg_z_score
0,229422,DIDNFDIDDFDDDDDWEDICII,0,4.094998,9.506665,12.105609,13.229315,14.031836,229609,976,...,5.0,19.0,256.0,270.0,1.900000e+00,23.1,3.574377,4.082822,4.670163,4.11
1,683178,LWQPHSSKQDDMWEHIAISML,0,4.420856,9.955033,12.104137,12.854852,13.584948,683868,244,...,1.0,17.0,465.0,481.0,4.550000e-07,42.0,3.573749,3.927170,4.482965,3.99
2,426137,VIEEADLDGDGSWALLTSRT,0,6.061220,10.521183,11.960512,12.786388,12.782009,426523,10,...,1.0,11.0,152.0,162.0,7.100000e-02,27.3,3.512489,3.898712,4.146620,3.85
3,480519,LHNPESGEEAVALLEELQRDLGWDILA,0,5.191722,10.334677,12.020974,12.594453,12.509488,480943,13,...,1.0,21.0,117.0,137.0,1.010000e-08,47.0,3.538278,3.818930,4.032463,3.80
4,810153,QIPENSTSSQADDEWCYVLI,0,5.148098,10.131437,11.838327,12.629829,12.705135,810989,91,...,1.0,10.0,552.0,561.0,1.400000e+00,23.5,3.460374,3.833635,4.114419,3.80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
968935,968935,YWITIDNPYVVAWHGYATGRLAPGIRGSPRLGYLVA,0,3.249749,NaN,NaN,NaN,NaN,969972,27,...,1.0,36.0,233.0,268.0,1.710000e-19,78.2,NaN,NaN,NaN,NaN
968939,968939,YWKESDKLLLIGLPAEEVPLPRLRNMIENVIQTLKF,0,2.764096,1.467049,-0.573207,NaN,NaN,969976,64,...,1.0,36.0,378.0,413.0,3.010000e-19,77.4,NaN,NaN,NaN,NaN
968940,968940,YWKNESGTWIQYGEEKDKRKNSNVDSSYLESLYQSC,0,0.565013,NaN,NaN,NaN,NaN,969977,31,...,1.0,36.0,610.0,645.0,8.820000e-20,79.0,NaN,NaN,NaN,NaN
968946,968946,YWKYGEAASTECNSVCFGDHTQPCGGDGRIILFDTL,0,NaN,NaN,NaN,NaN,NaN,969983,34,...,1.0,36.0,175.0,210.0,8.050000e-21,81.6,NaN,NaN,NaN,NaN
968947,968947,YWKYGEAASTACNSVCFGGSHPTVWWRWPYHPL,0,NaN,NaN,NaN,NaN,NaN,969984,11,...,1.0,18.0,175.0,192.0,4.000000e-06,40.0,NaN,NaN,NaN,NaN

In [85]:
df3 = df2[df2['avg_z_score']>=1.70]

In [86]:
df3

,Unnamed: 0,ID,ER 0_x,ER 1_x,ER 3_x,ER 4_x,ER 5_x,ER 6_x,Cluster Id_x,Input Count_x,...,Query start_x,Query End_x,Hit Start_x,Hit End_x,E-value_x,Score (Bits)_x,z_score_4,z_score_5,z_score_6,avg_z_score
0,229422,DIDNFDIDDFDDDDDWEDICII,0,4.094998,9.506665,12.105609,13.229315,14.031836,229609,976,...,5.0,19.0,256.0,270.0,1.900000e+00,23.1,3.574377,4.082822,4.670163,4.11
1,683178,LWQPHSSKQDDMWEHIAISML,0,4.420856,9.955033,12.104137,12.854852,13.584948,683868,244,...,1.0,17.0,465.0,481.0,4.550000e-07,42.0,3.573749,3.927170,4.482965,3.99
2,426137,VIEEADLDGDGSWALLTSRT,0,6.061220,10.521183,11.960512,12.786388,12.782009,426523,10,...,1.0,11.0,152.0,162.0,7.100000e-02,27.3,3.512489,3.898712,4.146620,3.85
3,480519,LHNPESGEEAVALLEELQRDLGWDILA,0,5.191722,10.334677,12.020974,12.594453,12.509488,480943,13,...,1.0,21.0,117.0,137.0,1.010000e-08,47.0,3.538278,3.818930,4.032463,3.80
4,810153,QIPENSTSSQADDEWCYVLI,0,5.148098,10.131437,11.838327,12.629829,12.705135,810989,91,...,1.0,10.0,552.0,561.0,1.400000e+00,23.5,3.460374,3.833635,4.114419,3.80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
422,136623,ASQGSDDDWDDEWDDSSTVADEPGALGSGAYPDLDG,0,6.093138,7.077381,7.625063,7.758434,6.743610,136733,28,...,1.0,36.0,146.0,181.0,1.450000e-17,72.4,1.663313,1.808750,1.617183,1.70
423,608085,LEATGPGGSQAINNLRRSNSTTQVSQPRSGSPRPTE,0,6.929649,7.823032,8.205766,7.752720,6.165534,608664,11,...,1.0,36.0,59.0,94.0,3.150000e-18,74.3,1.910997,1.806375,1.375032,1.70
424,654755,MPNTSVVLDTDAEFVILLLFLLLLFFFFRASFA,0,4.431676,7.914457,8.140802,7.387363,6.622837,655397,407,...,1.0,15.0,642.0,656.0,1.750000e-04,35.4,1.883288,1.654507,1.566592,1.70
425,723996,MSQAVQQRYSTIKQNMGTQFI,0,3.409332,7.021036,7.790198,7.932998,6.418514,724743,48,...,NaN,NaN,NaN,NaN,NaN,NaN,1.733747,1.881311,1.481003,1.70
426,861200,RVVNGAFMVLKGHRSIVNQARFNPHTYMICSLV,0,5.037973,6.692744,7.307211,7.830723,7.013530,862092,11,...,1.0,31.0,320.0,350.0,4.730000e-17,70.9,1.527741,1.838798,1.730251,1.70

In [87]:
pattern = r'HPQ'

# Filter rows where 'ID' matches the motif
df4 = df3[~df3['ID'].str.contains(pattern, regex=True)]

In [88]:
df4

,Unnamed: 0,ID,ER 0_x,ER 1_x,ER 3_x,ER 4_x,ER 5_x,ER 6_x,Cluster Id_x,Input Count_x,...,Query start_x,Query End_x,Hit Start_x,Hit End_x,E-value_x,Score (Bits)_x,z_score_4,z_score_5,z_score_6,avg_z_score
0,229422,DIDNFDIDDFDDDDDWEDICII,0,4.094998,9.506665,12.105609,13.229315,14.031836,229609,976,...,5.0,19.0,256.0,270.0,1.900000e+00,23.1,3.574377,4.082822,4.670163,4.11
1,683178,LWQPHSSKQDDMWEHIAISML,0,4.420856,9.955033,12.104137,12.854852,13.584948,683868,244,...,1.0,17.0,465.0,481.0,4.550000e-07,42.0,3.573749,3.927170,4.482965,3.99
2,426137,VIEEADLDGDGSWALLTSRT,0,6.061220,10.521183,11.960512,12.786388,12.782009,426523,10,...,1.0,11.0,152.0,162.0,7.100000e-02,27.3,3.512489,3.898712,4.146620,3.85
3,480519,LHNPESGEEAVALLEELQRDLGWDILA,0,5.191722,10.334677,12.020974,12.594453,12.509488,480943,13,...,1.0,21.0,117.0,137.0,1.010000e-08,47.0,3.538278,3.818930,4.032463,3.80
4,810153,QIPENSTSSQADDEWCYVLI,0,5.148098,10.131437,11.838327,12.629829,12.705135,810989,91,...,1.0,10.0,552.0,561.0,1.400000e+00,23.5,3.460374,3.833635,4.114419,3.80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
422,136623,ASQGSDDDWDDEWDDSSTVADEPGALGSGAYPDLDG,0,6.093138,7.077381,7.625063,7.758434,6.743610,136733,28,...,1.0,36.0,146.0,181.0,1.450000e-17,72.4,1.663313,1.808750,1.617183,1.70
423,608085,LEATGPGGSQAINNLRRSNSTTQVSQPRSGSPRPTE,0,6.929649,7.823032,8.205766,7.752720,6.165534,608664,11,...,1.0,36.0,59.0,94.0,3.150000e-18,74.3,1.910997,1.806375,1.375032,1.70
424,654755,MPNTSVVLDTDAEFVILLLFLLLLFFFFRASFA,0,4.431676,7.914457,8.140802,7.387363,6.622837,655397,407,...,1.0,15.0,642.0,656.0,1.750000e-04,35.4,1.883288,1.654507,1.566592,1.70
425,723996,MSQAVQQRYSTIKQNMGTQFI,0,3.409332,7.021036,7.790198,7.932998,6.418514,724743,48,...,NaN,NaN,NaN,NaN,NaN,NaN,1.733747,1.881311,1.481003,1.70
426,861200,RVVNGAFMVLKGHRSIVNQARFNPHTYMICSLV,0,5.037973,6.692744,7.307211,7.830723,7.013530,862092,11,...,1.0,31.0,320.0,350.0,4.730000e-17,70.9,1.527741,1.838798,1.730251,1.70

In [89]:
import re

pattern = re.compile(r"(?=([FWY]..[LVIFWY]))")  # lookahead captures overlapping matches

def extract_7mers(seq):
    matches = []
    found = re.findall(pattern, seq)  # gives list of matching substrings

    # walk through the sequence and look for each match's position
    for motif in found:
        # find the start position of the motif (could be multiple identical motifs, so loop!)
        start_idx = 0
        while True:
            start = seq.find(motif, start_idx)
            if start == -1:
                break
            if start >= 3:
                seven_mer = seq[start - 3 : start + 4]
                matches.append(seven_mer)
            start_idx = start + 1  # allow overlapping matches
    return matches


df4['ID2'] = 'PLR' + df4['ID']
df4['7mers'] = df4['ID2'].apply(extract_7mers)
df4 = df4[df4['7mers'].str.len() > 0]
df_7mers = df4.explode('7mers').reset_index(drop=True)

/var/folders/2c/6s7hc_xd4wj4sty6v7mf05n00000gn/T/ipykernel_55974/2824297181.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df4['ID2'] = 'PLR' + df4['ID']
/var/folders/2c/6s7hc_xd4wj4sty6v7mf05n00000gn/T/ipykernel_55974/2824297181.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df4['7mers'] = df4['ID2'].apply(extract_7mers)

In [90]:
df_7mers

,Unnamed: 0,ID,ER 0_x,ER 1_x,ER 3_x,ER 4_x,ER 5_x,ER 6_x,Cluster Id_x,Input Count_x,...,Hit Start_x,Hit End_x,E-value_x,Score (Bits)_x,z_score_4,z_score_5,z_score_6,avg_z_score,ID2,7mers
0,229422,DIDNFDIDDFDDDDDWEDICII,0,4.094998,9.506665,12.105609,13.229315,14.031836,229609,976,...,256.0,270.0,1.900000e+00,23.1,3.574377,4.082822,4.670163,4.11,PLRDIDNFDIDDFDDDDDWEDICII,DDDWEDI
1,683178,LWQPHSSKQDDMWEHIAISML,0,4.420856,9.955033,12.104137,12.854852,13.584948,683868,244,...,465.0,481.0,4.550000e-07,42.0,3.573749,3.927170,4.482965,3.99,PLRLWQPHSSKQDDMWEHIAISML,DDMWEHI
2,426137,VIEEADLDGDGSWALLTSRT,0,6.061220,10.521183,11.960512,12.786388,12.782009,426523,10,...,152.0,162.0,7.100000e-02,27.3,3.512489,3.898712,4.146620,3.85,PLRVIEEADLDGDGSWALLTSRT,DGSWALL
3,480519,LHNPESGEEAVALLEELQRDLGWDILA,0,5.191722,10.334677,12.020974,12.594453,12.509488,480943,13,...,117.0,137.0,1.010000e-08,47.0,3.538278,3.818930,4.032463,3.80,PLRLHNPESGEEAVALLEELQRDLGWDILA,DLGWDIL
4,810153,QIPENSTSSQADDEWCYVLI,0,5.148098,10.131437,11.838327,12.629829,12.705135,810989,91,...,552.0,561.0,1.400000e+00,23.5,3.460374,3.833635,4.114419,3.80,PLRQIPENSTSSQADDEWCYVLI,DDEWCYV
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
339,654755,MPNTSVVLDTDAEFVILLLFLLLLFFFFRASFA,0,4.431676,7.914457,8.140802,7.387363,6.622837,655397,407,...,642.0,656.0,1.750000e-04,35.4,1.883288,1.654507,1.566592,1.70,PLRMPNTSVVLDTDAEFVILLLFLLLLFFFFRASFA,DAEFVIL
340,654755,MPNTSVVLDTDAEFVILLLFLLLLFFFFRASFA,0,4.431676,7.914457,8.140802,7.387363,6.622837,655397,407,...,642.0,656.0,1.750000e-04,35.4,1.883288,1.654507,1.566592,1.70,PLRMPNTSVVLDTDAEFVILLLFLLLLFFFFRASFA,LLLFLLL
341,654755,MPNTSVVLDTDAEFVILLLFLLLLFFFFRASFA,0,4.431676,7.914457,8.140802,7.387363,6.622837,655397,407,...,642.0,656.0,1.750000e-04,35.4,1.883288,1.654507,1.566592,1.70,PLRMPNTSVVLDTDAEFVILLLFLLLLFFFFRASFA,LLLFFFF
342,723996,MSQAVQQRYSTIKQNMGTQFI,0,3.409332,7.021036,7.790198,7.932998,6.418514,724743,48,...,NaN,NaN,NaN,NaN,1.733747,1.881311,1.481003,1.70,PLRMSQAVQQRYSTIKQNMGTQFI,QQRYSTI
343,861200,RVVNGAFMVLKGHRSIVNQARFNPHTYMICSLV,0,5.037973,6.692744,7.307211,7.830723,7.013530,862092,11,...,320.0,350.0,4.730000e-17,70.9,1.527741,1.838798,1.730251,1.70,PLRRVVNGAFMVLKGHRSIVNQARFNPHTYMICSLV,NGAFMVL

In [92]:
df_7mers_filt = df_7mers[df_7mers.duplicated('ID2', keep=False) == False].copy()

In [93]:
df_7mers_filt

,Unnamed: 0,ID,ER 0_x,ER 1_x,ER 3_x,ER 4_x,ER 5_x,ER 6_x,Cluster Id_x,Input Count_x,...,Hit Start_x,Hit End_x,E-value_x,Score (Bits)_x,z_score_4,z_score_5,z_score_6,avg_z_score,ID2,7mers
0,229422,DIDNFDIDDFDDDDDWEDICII,0,4.094998,9.506665,12.105609,13.229315,14.031836,229609,976,...,256.0,270.0,1.900000e+00,23.1,3.574377,4.082822,4.670163,4.11,PLRDIDNFDIDDFDDDDDWEDICII,DDDWEDI
1,683178,LWQPHSSKQDDMWEHIAISML,0,4.420856,9.955033,12.104137,12.854852,13.584948,683868,244,...,465.0,481.0,4.550000e-07,42.0,3.573749,3.927170,4.482965,3.99,PLRLWQPHSSKQDDMWEHIAISML,DDMWEHI
2,426137,VIEEADLDGDGSWALLTSRT,0,6.061220,10.521183,11.960512,12.786388,12.782009,426523,10,...,152.0,162.0,7.100000e-02,27.3,3.512489,3.898712,4.146620,3.85,PLRVIEEADLDGDGSWALLTSRT,DGSWALL
3,480519,LHNPESGEEAVALLEELQRDLGWDILA,0,5.191722,10.334677,12.020974,12.594453,12.509488,480943,13,...,117.0,137.0,1.010000e-08,47.0,3.538278,3.818930,4.032463,3.80,PLRLHNPESGEEAVALLEELQRDLGWDILA,DLGWDIL
10,139933,ASTISSNASKGREAMEWVIIN,0,5.985777,9.823032,11.826119,12.320888,12.062774,140043,11,...,146.0,164.0,1.280000e-06,40.4,3.455167,3.705218,3.845338,3.67,PLRASTISSNASKGREAMEWVIIN,AMEWVII
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336,692007,MARVPLTFSDVAIASLRRSGNI,0,4.497790,6.555125,7.338737,7.601655,7.303037,692708,19,...,1.0,13.0,5.000000e-03,30.4,1.541188,1.743582,1.851523,1.71,PLRMARVPLTFSDVAIASLRRSGNI,PLTFSDV
337,102392,HLAAGYNNLEVAEYLLEHGADVNAQTRVV,0,4.039740,7.065926,7.296732,7.828102,7.030019,102470,29,...,842.0,868.0,3.130000e-11,54.3,1.523272,1.837709,1.737157,1.70,PLRHLAAGYNNLEVAEYLLEHGADVNAQTRVV,AAGYNNL
338,136623,ASQGSDDDWDDEWDDSSTVADEPGALGSGAYPDLDG,0,6.093138,7.077381,7.625063,7.758434,6.743610,136733,28,...,146.0,181.0,1.450000e-17,72.4,1.663313,1.808750,1.617183,1.70,PLRASQGSDDDWDDEWDDSSTVADEPGALGSGAYPDLDG,SGAYPDL
342,723996,MSQAVQQRYSTIKQNMGTQFI,0,3.409332,7.021036,7.790198,7.932998,6.418514,724743,48,...,NaN,NaN,NaN,NaN,1.733747,1.881311,1.481003,1.70,PLRMSQAVQQRYSTIKQNMGTQFI,QQRYSTI
343,861200,RVVNGAFMVLKGHRSIVNQARFNPHTYMICSLV,0,5.037973,6.692744,7.307211,7.830723,7.013530,862092,11,...,320.0,350.0,4.730000e-17,70.9,1.527741,1.838798,1.730251,1.70,PLRRVVNGAFMVLKGHRSIVNQARFNPHTYMICSLV,NGAFMVL

Generating background file

In [115]:
df2

,Unnamed: 0,ID,ER 0_x,ER 1_x,ER 3_x,ER 4_x,ER 5_x,ER 6_x,Cluster Id_x,Input Count_x,...,Query start_x,Query End_x,Hit Start_x,Hit End_x,E-value_x,Score (Bits)_x,z_score_4,z_score_5,z_score_6,avg_z_score
0,229422,DIDNFDIDDFDDDDDWEDICII,0,4.094998,9.506665,12.105609,13.229315,14.031836,229609,976,...,5.0,19.0,256.0,270.0,1.900000e+00,23.1,3.574377,4.082822,4.670163,4.11
1,683178,LWQPHSSKQDDMWEHIAISML,0,4.420856,9.955033,12.104137,12.854852,13.584948,683868,244,...,1.0,17.0,465.0,481.0,4.550000e-07,42.0,3.573749,3.927170,4.482965,3.99
2,426137,VIEEADLDGDGSWALLTSRT,0,6.061220,10.521183,11.960512,12.786388,12.782009,426523,10,...,1.0,11.0,152.0,162.0,7.100000e-02,27.3,3.512489,3.898712,4.146620,3.85
3,480519,LHNPESGEEAVALLEELQRDLGWDILA,0,5.191722,10.334677,12.020974,12.594453,12.509488,480943,13,...,1.0,21.0,117.0,137.0,1.010000e-08,47.0,3.538278,3.818930,4.032463,3.80
4,810153,QIPENSTSSQADDEWCYVLI,0,5.148098,10.131437,11.838327,12.629829,12.705135,810989,91,...,1.0,10.0,552.0,561.0,1.400000e+00,23.5,3.460374,3.833635,4.114419,3.80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
968935,968935,YWITIDNPYVVAWHGYATGRLAPGIRGSPRLGYLVA,0,3.249749,NaN,NaN,NaN,NaN,969972,27,...,1.0,36.0,233.0,268.0,1.710000e-19,78.2,NaN,NaN,NaN,NaN
968939,968939,YWKESDKLLLIGLPAEEVPLPRLRNMIENVIQTLKF,0,2.764096,1.467049,-0.573207,NaN,NaN,969976,64,...,1.0,36.0,378.0,413.0,3.010000e-19,77.4,NaN,NaN,NaN,NaN
968940,968940,YWKNESGTWIQYGEEKDKRKNSNVDSSYLESLYQSC,0,0.565013,NaN,NaN,NaN,NaN,969977,31,...,1.0,36.0,610.0,645.0,8.820000e-20,79.0,NaN,NaN,NaN,NaN
968946,968946,YWKYGEAASTECNSVCFGDHTQPCGGDGRIILFDTL,0,NaN,NaN,NaN,NaN,NaN,969983,34,...,1.0,36.0,175.0,210.0,8.050000e-21,81.6,NaN,NaN,NaN,NaN
968947,968947,YWKYGEAASTACNSVCFGGSHPTVWWRWPYHPL,0,NaN,NaN,NaN,NaN,NaN,969984,11,...,1.0,18.0,175.0,192.0,4.000000e-06,40.0,NaN,NaN,NaN,NaN

In [116]:
pattern = r'HPQ'

# Filter rows where 'ID' matches the motif
df2 = df2[~df2['ID'].str.contains(pattern, regex=True)]

In [117]:
df2.fillna(0, inplace=True)

/var/folders/2c/6s7hc_xd4wj4sty6v7mf05n00000gn/T/ipykernel_55974/3108480940.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.fillna(0, inplace=True)

In [118]:
df_input = df2[
    (df2['Input Count_x'] >= 50) &
    (df2['ER 1_x'] < 0) &
    (df2['ER 3_x'] < 0) &
    (df2['ER 4_x'] == 0) &
    (df2['ER 5_x'] == 0) &
    (df2['ER 6_x'] == 0)
].copy()

In [119]:
df_input

,Unnamed: 0,ID,ER 0_x,ER 1_x,ER 3_x,ER 4_x,ER 5_x,ER 6_x,Cluster Id_x,Input Count_x,...,Query start_x,Query End_x,Hit Start_x,Hit End_x,E-value_x,Score (Bits)_x,z_score_4,z_score_5,z_score_6,avg_z_score
12187,30,LKSQGGDGFYGRECDWWSVGVFLYEILVGDTPFYAD,0,-6.508351,-8.289520,0.0,0.0,0.0,31,2171,...,1.0,36.0,262.0,297.0,9.510000e-23,87.4,0.0,0.0,0.0,0.0
12287,131,HFLDVMAAGKRLMCGFFSPLFIHSCIHLFNAFYCV,0,-2.410049,-2.490778,0.0,0.0,0.0,133,117,...,11.0,34.0,889.0,912.0,2.500000e+00,23.9,0.0,0.0,0.0,0.0
12340,184,ADGLFLLRQCLRSLGGYVLSLVHDVRFHHFPIERQL,0,-1.526745,-1.829867,0.0,0.0,0.0,186,74,...,1.0,36.0,30.0,65.0,2.960000e-21,83.2,0.0,0.0,0.0,0.0
12375,219,PAGLSTSADGFLKPPAGSVPGPDSPGELFLKLPPQV,0,-1.665215,-1.398021,0.0,0.0,0.0,221,64,...,1.0,36.0,2132.0,2167.0,4.020000e-17,71.2,0.0,0.0,0.0,0.0
12449,294,ADGNWMGIVDPFARPRGHGRKGEDALCRYFSNERIP,0,-0.693755,-1.397793,0.0,0.0,0.0,297,905,...,1.0,36.0,436.0,471.0,1.250000e-22,87.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
966613,966597,YTGPKQDVRAARDFILKLYQDQNPDKEKVIYSHFTC,0,-5.334100,-2.829867,0.0,0.0,0.0,967631,74,...,1.0,36.0,291.0,326.0,1.060000e-20,80.9,0.0,0.0,0.0,0.0
966618,966602,YTGWMQKWPTLQDLASASLEEVNQLWAGLGYYSRAS,0,-0.942809,-1.464110,0.0,0.0,0.0,967636,67,...,1.0,34.0,146.0,179.0,1.200000e-18,75.5,0.0,0.0,0.0,0.0
967541,967528,YYLKHFIHVLQTGQLNQKLGVSLLVIVLEAFHFDHK,0,-1.985941,-1.973560,0.0,0.0,0.0,968564,109,...,1.0,36.0,1654.0,1689.0,1.410000e-18,75.5,0.0,0.0,0.0,0.0
968591,968587,YVNVSRGLFEQHKLIYSFMLCVEMMRQQGTLSDAEW,0,-5.063246,-4.143976,0.0,0.0,0.0,969624,184,...,1.0,36.0,3355.0,3390.0,8.250000e-21,81.6,0.0,0.0,0.0,0.0
968705,968702,YVSTIRIPIRRILNTGLSETTSVAIQTMLRQIMTGF,0,-4.932002,-4.427769,0.0,0.0,0.0,969739,224,...,1.0,36.0,378.0,413.0,4.640000e-18,73.9,0.0,0.0,0.0,0.0

In [120]:
import re

pattern = re.compile(r"(?=([FWY]..[LVIFWY]))")  # lookahead captures overlapping matches

def extract_7mers(seq):
    matches = []
    found = re.findall(pattern, seq)  # gives list of matching substrings

    # walk through the sequence and look for each match's position
    for motif in found:
        # find the start position of the motif (could be multiple identical motifs, so loop!)
        start_idx = 0
        while True:
            start = seq.find(motif, start_idx)
            if start == -1:
                break
            if start >= 3:
                seven_mer = seq[start - 3 : start + 4]
                matches.append(seven_mer)
            start_idx = start + 1  # allow overlapping matches
    return matches


df_input['ID2'] = 'PLR' + df_input['ID']
df_input['7mers'] = df_input['ID2'].apply(extract_7mers)
df_input = df_input[df_input['7mers'].str.len() > 0]
df_input_7mers = df_input.explode('7mers').reset_index(drop=True)

df_input_filt = df_input_7mers[df_input_7mers.duplicated('ID2', keep=False) == False].copy()

In [121]:
df_input_filt

,Unnamed: 0,ID,ER 0_x,ER 1_x,ER 3_x,ER 4_x,ER 5_x,ER 6_x,Cluster Id_x,Input Count_x,...,Hit Start_x,Hit End_x,E-value_x,Score (Bits)_x,z_score_4,z_score_5,z_score_6,avg_z_score,ID2,7mers
6,184,ADGLFLLRQCLRSLGGYVLSLVHDVRFHHFPIERQL,0,-1.526745,-1.829867,0.0,0.0,0.0,186,74,...,30.0,65.0,2.960000e-21,83.2,0.0,0.0,0.0,0.0,PLRADGLFLLRQCLRSLGGYVLSLVHDVRFHHFPIERQL,DVRFHHF
7,219,PAGLSTSADGFLKPPAGSVPGPDSPGELFLKLPPQV,0,-1.665215,-1.398021,0.0,0.0,0.0,221,64,...,2132.0,2167.0,4.020000e-17,71.2,0.0,0.0,0.0,0.0,PLRPAGLSTSADGFLKPPAGSVPGPDSPGELFLKLPPQV,GELFLKL
8,294,ADGNWMGIVDPFARPRGHGRKGEDALCRYFSNERIP,0,-0.693755,-1.397793,0.0,0.0,0.0,297,905,...,436.0,471.0,1.250000e-22,87.0,0.0,0.0,0.0,0.0,PLRADGNWMGIVDPFARPRGHGRKGEDALCRYFSNERIP,DGNWMGI
11,467,ADGRKFGSKYLVDHEVHFTCNPGFRLVGPSSMVCLP,0,-4.063246,-3.506546,0.0,0.0,0.0,470,276,...,88.0,123.0,1.500000e-19,78.2,0.0,0.0,0.0,0.0,PLRADGRKFGSKYLVDHEVHFTCNPGFRLVGPSSMVCLP,NPGFRLV
12,663,AAGVDAGTPAPLRGVLCPLIWCLLLSLARGRQPLSR,0,-0.778872,-3.790339,0.0,0.0,0.0,666,384,...,68.0,80.0,3.100000e+00,23.5,0.0,0.0,0.0,0.0,PLRAAGVDAGTPAPLRGVLCPLIWCLLLSLARGRQPLSR,PLIWCLL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8631,961967,YLAVQLSPAIPVFAAMLFLFSMATLLRTSFSDPGVI,0,-3.094273,-4.344927,0.0,0.0,0.0,962994,141,...,59.0,94.0,5.850000e-17,70.5,0.0,0.0,0.0,0.0,PLRYLAVQLSPAIPVFAAMLFLFSMATLLRTSFSDPGVI,PLRYLAV
8636,963224,YMAAALLEFFTHLPSSSSMPPSTTSASTVLTGRVW,0,-2.329761,-1.258487,0.0,0.0,0.0,964253,83,...,445.0,475.0,5.300000e-01,25.8,0.0,0.0,0.0,0.0,PLRYMAAALLEFFTHLPSSSSMPPSTTSASTVLTGRVW,LEFFTHL
8644,966597,YTGPKQDVRAARDFILKLYQDQNPDKEKVIYSHFTC,0,-5.334100,-2.829867,0.0,0.0,0.0,967631,74,...,291.0,326.0,1.060000e-20,80.9,0.0,0.0,0.0,0.0,PLRYTGPKQDVRAARDFILKLYQDQNPDKEKVIYSHFTC,KVIYSHF
8648,967528,YYLKHFIHVLQTGQLNQKLGVSLLVIVLEAFHFDHK,0,-1.985941,-1.973560,0.0,0.0,0.0,968564,109,...,1654.0,1689.0,1.410000e-18,75.5,0.0,0.0,0.0,0.0,PLRYYLKHFIHVLQTGQLNQKLGVSLLVIVLEAFHFDHK,LKHFIHV
8649,968587,YVNVSRGLFEQHKLIYSFMLCVEMMRQQGTLSDAEW,0,-5.063246,-4.143976,0.0,0.0,0.0,969624,184,...,3355.0,3390.0,8.250000e-21,81.6,0.0,0.0,0.0,0.0,PLRYVNVSRGLFEQHKLIYSFMLCVEMMRQQGTLSDAEW,PLRYVNV

In [ ]:
df_6 = pd.read_csv('/Users/jenniferkosmatka/MIT Dropbox/jhdavislab/06_davis_lab_papers/in_preparation/03_lc3bscreen_jk/supporting data/SF4_S6peptides_zscore.csv')

In [66]:
df_6

,0,1,3,4,5,6,Clust group,ID,Cluster Id,Input Count,...,SeqStop,E-value,Score (Bits),ProteinAcc,ave AF2 pLDDT - motif,highest AF2 pLDDT - motif,z_score_4,z_score_5,z_score_6,avg_z_score
0,0,4.094998,9.506665,12.105609,13.229315,14.031836,10,DIDNFDIDDFDDDDDWEDICII,229609,976,...,270.0,1.900000e+00,23.1,P49336,NaN,NaN,3.574377,4.082822,4.670163,4.109121
1,0,4.420856,9.955033,12.104137,12.854852,13.584948,10,LWQPHSSKQDDMWEHIAISML,683868,244,...,481.0,4.550000e-07,42.0,Q96RS6,90.877647,98.12,3.573749,3.927170,4.482965,3.994628
2,0,6.061220,10.521183,11.960512,12.786388,12.782009,10,VIEEADLDGDGSWALLTSRT,426523,10,...,162.0,7.100000e-02,27.3,O75838,91.690909,93.80,3.512489,3.898712,4.146620,3.852607
3,0,5.148098,10.131437,11.838327,12.629829,12.705135,10,QIPENSTSSQADDEWCYVLI,810989,91,...,561.0,1.400000e+00,23.5,O15062,36.374000,39.71,3.460374,3.833635,4.114419,3.802809
4,0,5.191722,10.334677,12.020974,12.594453,12.509488,10,LHNPESGEEAVALLEELQRDLGWDILA,480943,13,...,137.0,1.010000e-08,47.0,P59923,84.035238,89.15,3.538278,3.818930,4.032463,3.796557
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12153,0,-1.324078,-4.685156,-4.512419,-3.312022,-4.636175,4,CDKCILKMDHHCPWVNNCVGFSNYKFFLLFLAYSLL,131946,3927,...,181.0,2.050000e-20,80.1,Q9UIJ5,98.272222,98.81,-3.513623,-2.792889,-3.149718,-3.152077
12154,0,-6.737252,-7.625336,-5.993167,-3.377733,-3.116923,4,LVFIVLFTGECVLKLISLRHYYFTIGWNIFDFVVVI,169849,1370,...,1613.0,2.510000e-19,77.4,P35498,87.861389,92.62,-4.145199,-2.820202,-2.513315,-3.159572
12155,0,-2.464264,-5.536462,-4.824859,-5.016779,-4.755969,4,HTGIKPYECKECGQAFAQYSGLLFTFVVTVVRNRI,37351,8534,...,352.0,2.800000e-10,52.0,Q8N587,85.830909,93.21,-3.646886,-3.501502,-3.199899,-3.449429
12156,0,-0.203679,-2.711897,-6.177760,-4.562326,-4.301516,4,QPPQNPYYMWTGIRTSSSKFRRKTMPSATTSMKPQ,322474,3114,...,266.0,1.100000e-01,27.7,Q7Z3Z4,NaN,NaN,-4.223932,-3.312600,-3.009532,-3.515355
12157,0,-2.859186,-6.134293,-6.202564,-4.587130,-4.326320,4,SHFHERHKCINFFVKVYGYMPLLYTQFRVDSVLFKT,65031,3168,...,906.0,1.090000e-21,84.3,O43909,92.946389,98.36,-4.234512,-3.322910,-3.019922,-3.525781

In [67]:
df_6['avg_z_score'] = df_6['avg_z_score'].round(2)

In [68]:
df_7 = df_6[df_6['avg_z_score']>=1.70]

In [69]:
df_7

,0,1,3,4,5,6,Clust group,ID,Cluster Id,Input Count,...,SeqStop,E-value,Score (Bits),ProteinAcc,ave AF2 pLDDT - motif,highest AF2 pLDDT - motif,z_score_4,z_score_5,z_score_6,avg_z_score
0,0,4.094998,9.506665,12.105609,13.229315,14.031836,10,DIDNFDIDDFDDDDDWEDICII,229609,976,...,270.0,1.900000e+00,23.1,P49336,NaN,NaN,3.574377,4.082822,4.670163,4.11
1,0,4.420856,9.955033,12.104137,12.854852,13.584948,10,LWQPHSSKQDDMWEHIAISML,683868,244,...,481.0,4.550000e-07,42.0,Q96RS6,90.877647,98.12,3.573749,3.927170,4.482965,3.99
2,0,6.061220,10.521183,11.960512,12.786388,12.782009,10,VIEEADLDGDGSWALLTSRT,426523,10,...,162.0,7.100000e-02,27.3,O75838,91.690909,93.80,3.512489,3.898712,4.146620,3.85
3,0,5.148098,10.131437,11.838327,12.629829,12.705135,10,QIPENSTSSQADDEWCYVLI,810989,91,...,561.0,1.400000e+00,23.5,O15062,36.374000,39.71,3.460374,3.833635,4.114419,3.80
4,0,5.191722,10.334677,12.020974,12.594453,12.509488,10,LHNPESGEEAVALLEELQRDLGWDILA,480943,13,...,137.0,1.010000e-08,47.0,P59923,84.035238,89.15,3.538278,3.818930,4.032463,3.80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
422,0,4.039740,7.065926,7.296732,7.828102,7.030019,9,HLAAGYNNLEVAEYLLEHGADVNAQTRVV,102470,29,...,868.0,3.130000e-11,54.3,O95271,96.848889,98.31,1.523272,1.837709,1.737157,1.70
423,0,5.037973,6.692744,7.307211,7.830723,7.013530,9,RVVNGAFMVLKGHRSIVNQARFNPHTYMICSLV,862092,11,...,350.0,4.730000e-17,70.9,Q96JK2,93.258387,98.41,1.527741,1.838798,1.730251,1.70
424,0,3.409332,7.021036,7.790198,7.932998,6.418514,9,MSQAVQQRYSTIKQNMGTQFI,724743,48,...,NaN,NaN,NaN,NaN,NaN,NaN,1.733747,1.881311,1.481003,1.70
425,0,6.929649,7.823032,8.205766,7.752720,6.165534,9,LEATGPGGSQAINNLRRSNSTTQVSQPRSGSPRPTE,608664,11,...,94.0,3.150000e-18,74.3,Q9UPN4,32.552500,38.02,1.910997,1.806375,1.375032,1.70
426,0,6.093138,7.077381,7.625063,7.758434,6.743610,9,ASQGSDDDWDDEWDDSSTVADEPGALGSGAYPDLDG,136733,28,...,181.0,1.450000e-17,72.4,Q96RF0,32.497222,47.27,1.663313,1.808750,1.617183,1.70

In [70]:
pattern = r'HPQ'

# Filter rows where 'ID' matches the motif
df8 = df_7[~df_7['ID'].str.contains(pattern, regex=True)]

In [71]:
df8

,0,1,3,4,5,6,Clust group,ID,Cluster Id,Input Count,...,SeqStop,E-value,Score (Bits),ProteinAcc,ave AF2 pLDDT - motif,highest AF2 pLDDT - motif,z_score_4,z_score_5,z_score_6,avg_z_score
0,0,4.094998,9.506665,12.105609,13.229315,14.031836,10,DIDNFDIDDFDDDDDWEDICII,229609,976,...,270.0,1.900000e+00,23.1,P49336,NaN,NaN,3.574377,4.082822,4.670163,4.11
1,0,4.420856,9.955033,12.104137,12.854852,13.584948,10,LWQPHSSKQDDMWEHIAISML,683868,244,...,481.0,4.550000e-07,42.0,Q96RS6,90.877647,98.12,3.573749,3.927170,4.482965,3.99
2,0,6.061220,10.521183,11.960512,12.786388,12.782009,10,VIEEADLDGDGSWALLTSRT,426523,10,...,162.0,7.100000e-02,27.3,O75838,91.690909,93.80,3.512489,3.898712,4.146620,3.85
3,0,5.148098,10.131437,11.838327,12.629829,12.705135,10,QIPENSTSSQADDEWCYVLI,810989,91,...,561.0,1.400000e+00,23.5,O15062,36.374000,39.71,3.460374,3.833635,4.114419,3.80
4,0,5.191722,10.334677,12.020974,12.594453,12.509488,10,LHNPESGEEAVALLEELQRDLGWDILA,480943,13,...,137.0,1.010000e-08,47.0,P59923,84.035238,89.15,3.538278,3.818930,4.032463,3.80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
422,0,4.039740,7.065926,7.296732,7.828102,7.030019,9,HLAAGYNNLEVAEYLLEHGADVNAQTRVV,102470,29,...,868.0,3.130000e-11,54.3,O95271,96.848889,98.31,1.523272,1.837709,1.737157,1.70
423,0,5.037973,6.692744,7.307211,7.830723,7.013530,9,RVVNGAFMVLKGHRSIVNQARFNPHTYMICSLV,862092,11,...,350.0,4.730000e-17,70.9,Q96JK2,93.258387,98.41,1.527741,1.838798,1.730251,1.70
424,0,3.409332,7.021036,7.790198,7.932998,6.418514,9,MSQAVQQRYSTIKQNMGTQFI,724743,48,...,NaN,NaN,NaN,NaN,NaN,NaN,1.733747,1.881311,1.481003,1.70
425,0,6.929649,7.823032,8.205766,7.752720,6.165534,9,LEATGPGGSQAINNLRRSNSTTQVSQPRSGSPRPTE,608664,11,...,94.0,3.150000e-18,74.3,Q9UPN4,32.552500,38.02,1.910997,1.806375,1.375032,1.70
426,0,6.093138,7.077381,7.625063,7.758434,6.743610,9,ASQGSDDDWDDEWDDSSTVADEPGALGSGAYPDLDG,136733,28,...,181.0,1.450000e-17,72.4,Q96RF0,32.497222,47.27,1.663313,1.808750,1.617183,1.70

In [72]:
import re

pattern = r'[FWY]..[LVIFWY]'

def extract_7mers(seq):
    matches = []
    for match in re.finditer(pattern, seq):
        start = match.start()
        if start >= 3:  # Ensure there are 3 residues before the motif
            seven_mer = seq[start-3:start+4]
            matches.append(seven_mer)
    return matches
df8['ID2'] = 'PLR' + df8['ID']
# Apply to the DataFrame
df8['7mers'] = df8['ID2'].apply(extract_7mers)

# Drop rows with no 7-mers
df8 = df8[df8['7mers'].str.len() > 0]

# Explode so each 7-mer is its own row
df_7mers2 = df8.explode('7mers').reset_index(drop=True)

/var/folders/2c/6s7hc_xd4wj4sty6v7mf05n00000gn/T/ipykernel_55974/3082156275.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df8['ID2'] = 'PLR' + df8['ID']
/var/folders/2c/6s7hc_xd4wj4sty6v7mf05n00000gn/T/ipykernel_55974/3082156275.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df8['7mers'] = df8['ID2'].apply(extract_7mers)

In [73]:
df_7mers2

,0,1,3,4,5,6,Clust group,ID,Cluster Id,Input Count,...,Score (Bits),ProteinAcc,ave AF2 pLDDT - motif,highest AF2 pLDDT - motif,z_score_4,z_score_5,z_score_6,avg_z_score,ID2,7mers
0,0,4.094998,9.506665,12.105609,13.229315,14.031836,10,DIDNFDIDDFDDDDDWEDICII,229609,976,...,23.1,P49336,NaN,NaN,3.574377,4.082822,4.670163,4.11,PLRDIDNFDIDDFDDDDDWEDICII,DDDWEDI
1,0,4.420856,9.955033,12.104137,12.854852,13.584948,10,LWQPHSSKQDDMWEHIAISML,683868,244,...,42.0,Q96RS6,90.877647,98.12,3.573749,3.927170,4.482965,3.99,PLRLWQPHSSKQDDMWEHIAISML,DDMWEHI
2,0,6.061220,10.521183,11.960512,12.786388,12.782009,10,VIEEADLDGDGSWALLTSRT,426523,10,...,27.3,O75838,91.690909,93.80,3.512489,3.898712,4.146620,3.85,PLRVIEEADLDGDGSWALLTSRT,DGSWALL
3,0,5.148098,10.131437,11.838327,12.629829,12.705135,10,QIPENSTSSQADDEWCYVLI,810989,91,...,23.5,O15062,36.374000,39.71,3.460374,3.833635,4.114419,3.80,PLRQIPENSTSSQADDEWCYVLI,DDEWCYV
4,0,5.191722,10.334677,12.020974,12.594453,12.509488,10,LHNPESGEEAVALLEELQRDLGWDILA,480943,13,...,47.0,P59923,84.035238,89.15,3.538278,3.818930,4.032463,3.80,PLRLHNPESGEEAVALLEELQRDLGWDILA,DLGWDIL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
302,0,4.431676,7.914457,8.140802,7.387363,6.622837,9,MPNTSVVLDTDAEFVILLLFLLLLFFFFRASFA,655397,407,...,35.4,Q9ULI3,32.240667,35.42,1.883288,1.654507,1.566592,1.70,PLRMPNTSVVLDTDAEFVILLLFLLLLFFFFRASFA,LLLFFFF
303,0,4.039740,7.065926,7.296732,7.828102,7.030019,9,HLAAGYNNLEVAEYLLEHGADVNAQTRVV,102470,29,...,54.3,O95271,96.848889,98.31,1.523272,1.837709,1.737157,1.70,PLRHLAAGYNNLEVAEYLLEHGADVNAQTRVV,AAGYNNL
304,0,5.037973,6.692744,7.307211,7.830723,7.013530,9,RVVNGAFMVLKGHRSIVNQARFNPHTYMICSLV,862092,11,...,70.9,Q96JK2,93.258387,98.41,1.527741,1.838798,1.730251,1.70,PLRRVVNGAFMVLKGHRSIVNQARFNPHTYMICSLV,NGAFMVL
305,0,3.409332,7.021036,7.790198,7.932998,6.418514,9,MSQAVQQRYSTIKQNMGTQFI,724743,48,...,NaN,NaN,NaN,NaN,1.733747,1.881311,1.481003,1.70,PLRMSQAVQQRYSTIKQNMGTQFI,QQRYSTI
306,0,6.093138,7.077381,7.625063,7.758434,6.743610,9,ASQGSDDDWDDEWDDSSTVADEPGALGSGAYPDLDG,136733,28,...,72.4,Q96RF0,32.497222,47.27,1.663313,1.808750,1.617183,1.70,PLRASQGSDDDWDDEWDDSSTVADEPGALGSGAYPDLDG,SGAYPDL

In [74]:
import re

pattern = r'[FWY]..[LVIFWY]'

# Count matches in ID2
df_7mers2['motif_count'] = df_7mers2['ID2'].str.findall(pattern).str.len()

# Keep only rows with exactly one match
df_filtered = df_7mers2[df_7mers2['motif_count'] == 1].copy()

# Optional: drop the helper column
df_filtered.drop(columns='motif_count', inplace=True)

In [75]:
df_filtered

,0,1,3,4,5,6,Clust group,ID,Cluster Id,Input Count,...,Score (Bits),ProteinAcc,ave AF2 pLDDT - motif,highest AF2 pLDDT - motif,z_score_4,z_score_5,z_score_6,avg_z_score,ID2,7mers
0,0,4.094998,9.506665,12.105609,13.229315,14.031836,10,DIDNFDIDDFDDDDDWEDICII,229609,976,...,23.1,P49336,NaN,NaN,3.574377,4.082822,4.670163,4.11,PLRDIDNFDIDDFDDDDDWEDICII,DDDWEDI
1,0,4.420856,9.955033,12.104137,12.854852,13.584948,10,LWQPHSSKQDDMWEHIAISML,683868,244,...,42.0,Q96RS6,90.877647,98.12,3.573749,3.927170,4.482965,3.99,PLRLWQPHSSKQDDMWEHIAISML,DDMWEHI
2,0,6.061220,10.521183,11.960512,12.786388,12.782009,10,VIEEADLDGDGSWALLTSRT,426523,10,...,27.3,O75838,91.690909,93.80,3.512489,3.898712,4.146620,3.85,PLRVIEEADLDGDGSWALLTSRT,DGSWALL
3,0,5.148098,10.131437,11.838327,12.629829,12.705135,10,QIPENSTSSQADDEWCYVLI,810989,91,...,23.5,O15062,36.374000,39.71,3.460374,3.833635,4.114419,3.80,PLRQIPENSTSSQADDEWCYVLI,DDEWCYV
4,0,5.191722,10.334677,12.020974,12.594453,12.509488,10,LHNPESGEEAVALLEELQRDLGWDILA,480943,13,...,47.0,P59923,84.035238,89.15,3.538278,3.818930,4.032463,3.80,PLRLHNPESGEEAVALLEELQRDLGWDILA,DLGWDIL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299,0,4.665430,7.100432,7.199382,7.627190,7.381040,9,EVRFTNVPERTQIDVGRILYSV,339629,18,...,42.4,Q9H3R0,88.473333,92.69,1.481750,1.754196,1.884197,1.71,PLREVRFTNVPERTQIDVGRILYSV,EVRFTNV
303,0,4.039740,7.065926,7.296732,7.828102,7.030019,9,HLAAGYNNLEVAEYLLEHGADVNAQTRVV,102470,29,...,54.3,O95271,96.848889,98.31,1.523272,1.837709,1.737157,1.70,PLRHLAAGYNNLEVAEYLLEHGADVNAQTRVV,AAGYNNL
304,0,5.037973,6.692744,7.307211,7.830723,7.013530,9,RVVNGAFMVLKGHRSIVNQARFNPHTYMICSLV,862092,11,...,70.9,Q96JK2,93.258387,98.41,1.527741,1.838798,1.730251,1.70,PLRRVVNGAFMVLKGHRSIVNQARFNPHTYMICSLV,NGAFMVL
305,0,3.409332,7.021036,7.790198,7.932998,6.418514,9,MSQAVQQRYSTIKQNMGTQFI,724743,48,...,NaN,NaN,NaN,NaN,1.733747,1.881311,1.481003,1.70,PLRMSQAVQQRYSTIKQNMGTQFI,QQRYSTI
306,0,6.093138,7.077381,7.625063,7.758434,6.743610,9,ASQGSDDDWDDEWDDSSTVADEPGALGSGAYPDLDG,136733,28,...,72.4,Q96RF0,32.497222,47.27,1.663313,1.808750,1.617183,1.70,PLRASQGSDDDWDDEWDDSSTVADEPGALGSGAYPDLDG,SGAYPDL

In [1]:
import re
p = re.compile(r'[FWY]..[LVIFWY]')
p.findall('IHLFNAFYCV')

['FNAF']

In [2]:
import re
p = re.compile(r"(?=([FWY]..[LVIFWY]))")
p.findall('IHLFNAFYCV')

['FNAF', 'FYCV']