In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("/Users/jenniferkosmatka/MIT Dropbox/Jennifer Kosmatka/pssm_lc3b_lir-adjacent/data/raw/231209_completedata_JK.csv", sep="\t")

In [4]:
df

,Unnamed: 0,ID,ER 0,ER 1,ER 3,ER 4,ER 5,ER 6,Input Count,1 Count,...,Query start,Query End,Hit Start,Hit End,E-value,Score (Bits),z_score_4,z_score_5,z_score_6,avg_z_score
0,0,DIDNFDIDDFDDDDDWEDICII,0,4.094998,9.506665,12.105609,13.229315,14.031836,976,9092,...,5.0,19.0,256.0,270.0,1.900000e+00,23.1,3.574377,4.082822,4.670163,4.11
1,1,LWQPHSSKQDDMWEHIAISML,0,4.420856,9.955033,12.104137,12.854852,13.584948,244,2849,...,1.0,17.0,465.0,481.0,4.550000e-07,42.0,3.573749,3.927170,4.482965,3.99
2,2,VIEEADLDGDGSWALLTSRT,0,6.061220,10.521183,11.960512,12.786388,12.782009,10,364,...,1.0,11.0,152.0,162.0,7.100000e-02,27.3,3.512489,3.898712,4.146620,3.85
3,3,LHNPESGEEAVALLEELQRDLGWDILA,0,5.191722,10.334677,12.020974,12.594453,12.509488,13,259,...,1.0,21.0,117.0,137.0,1.010000e-08,47.0,3.538278,3.818930,4.032463,3.80
4,4,QIPENSTSSQADDEWCYVLI,0,5.148098,10.131437,11.838327,12.629829,12.705135,91,1759,...,1.0,10.0,552.0,561.0,1.400000e+00,23.5,3.460374,3.833635,4.114419,3.80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
966443,968944,YWKLTIMSFIKLMVVNPSILIVSFMVMKLPKMCMK,0,NaN,NaN,NaN,NaN,NaN,9,0,...,6.0,35.0,279.0,308.0,8.800000e+00,22.3,NaN,NaN,NaN,NaN
966444,968945,YWKNLPVCKPCPAASFLLCTEY,0,NaN,NaN,NaN,NaN,NaN,1,0,...,6.0,16.0,445.0,455.0,6.300000e+00,21.9,NaN,NaN,NaN,NaN
966445,968946,YWKYGEAASTECNSVCFGDHTQPCGGDGRIILFDTL,0,NaN,NaN,NaN,NaN,NaN,34,0,...,1.0,36.0,175.0,210.0,8.050000e-21,81.6,NaN,NaN,NaN,NaN
966446,968947,YWKYGEAASTACNSVCFGGSHPTVWWRWPYHPL,0,NaN,NaN,NaN,NaN,NaN,11,0,...,1.0,18.0,175.0,192.0,4.000000e-06,40.0,NaN,NaN,NaN,NaN
966447,968948,YWKYGEAAVPNATASASGITPNRVVAMAVSSSLIL,0,NaN,NaN,NaN,NaN,NaN,1,0,...,4.0,35.0,657.0,688.0,1.900000e-01,26.9,NaN,NaN,NaN,NaN

In [5]:
df = df[df['Input Count'] >=10]

In [6]:
df

,Unnamed: 0,ID,ER 0,ER 1,ER 3,ER 4,ER 5,ER 6,Input Count,1 Count,...,Query start,Query End,Hit Start,Hit End,E-value,Score (Bits),z_score_4,z_score_5,z_score_6,avg_z_score
0,0,DIDNFDIDDFDDDDDWEDICII,0,4.094998,9.506665,12.105609,13.229315,14.031836,976,9092,...,5.0,19.0,256.0,270.0,1.900000e+00,23.1,3.574377,4.082822,4.670163,4.11
1,1,LWQPHSSKQDDMWEHIAISML,0,4.420856,9.955033,12.104137,12.854852,13.584948,244,2849,...,1.0,17.0,465.0,481.0,4.550000e-07,42.0,3.573749,3.927170,4.482965,3.99
2,2,VIEEADLDGDGSWALLTSRT,0,6.061220,10.521183,11.960512,12.786388,12.782009,10,364,...,1.0,11.0,152.0,162.0,7.100000e-02,27.3,3.512489,3.898712,4.146620,3.85
3,3,LHNPESGEEAVALLEELQRDLGWDILA,0,5.191722,10.334677,12.020974,12.594453,12.509488,13,259,...,1.0,21.0,117.0,137.0,1.010000e-08,47.0,3.538278,3.818930,4.032463,3.80
4,4,QIPENSTSSQADDEWCYVLI,0,5.148098,10.131437,11.838327,12.629829,12.705135,91,1759,...,1.0,10.0,552.0,561.0,1.400000e+00,23.5,3.460374,3.833635,4.114419,3.80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
966434,968935,YWITIDNPYVVAWHGYATGRLAPGIRGSPRLGYLVA,0,3.249749,NaN,NaN,NaN,NaN,27,140,...,1.0,36.0,233.0,268.0,1.710000e-19,78.2,NaN,NaN,NaN,NaN
966438,968939,YWKESDKLLLIGLPAEEVPLPRLRNMIENVIQTLKF,0,2.764096,1.467049,-0.573207,NaN,NaN,64,237,...,1.0,36.0,378.0,413.0,3.010000e-19,77.4,NaN,NaN,NaN,NaN
966439,968940,YWKNESGTWIQYGEEKDKRKNSNVDSSYLESLYQSC,0,0.565013,NaN,NaN,NaN,NaN,31,25,...,1.0,36.0,610.0,645.0,8.820000e-20,79.0,NaN,NaN,NaN,NaN
966445,968946,YWKYGEAASTECNSVCFGDHTQPCGGDGRIILFDTL,0,NaN,NaN,NaN,NaN,NaN,34,0,...,1.0,36.0,175.0,210.0,8.050000e-21,81.6,NaN,NaN,NaN,NaN
966446,968947,YWKYGEAASTACNSVCFGGSHPTVWWRWPYHPL,0,NaN,NaN,NaN,NaN,NaN,11,0,...,1.0,18.0,175.0,192.0,4.000000e-06,40.0,NaN,NaN,NaN,NaN

In [7]:
df = df[df['avg_z_score']>=1.70]

In [8]:
df

,Unnamed: 0,ID,ER 0,ER 1,ER 3,ER 4,ER 5,ER 6,Input Count,1 Count,...,Query start,Query End,Hit Start,Hit End,E-value,Score (Bits),z_score_4,z_score_5,z_score_6,avg_z_score
0,0,DIDNFDIDDFDDDDDWEDICII,0,4.094998,9.506665,12.105609,13.229315,14.031836,976,9092,...,5.0,19.0,256.0,270.0,1.900000e+00,23.1,3.574377,4.082822,4.670163,4.11
1,1,LWQPHSSKQDDMWEHIAISML,0,4.420856,9.955033,12.104137,12.854852,13.584948,244,2849,...,1.0,17.0,465.0,481.0,4.550000e-07,42.0,3.573749,3.927170,4.482965,3.99
2,2,VIEEADLDGDGSWALLTSRT,0,6.061220,10.521183,11.960512,12.786388,12.782009,10,364,...,1.0,11.0,152.0,162.0,7.100000e-02,27.3,3.512489,3.898712,4.146620,3.85
3,3,LHNPESGEEAVALLEELQRDLGWDILA,0,5.191722,10.334677,12.020974,12.594453,12.509488,13,259,...,1.0,21.0,117.0,137.0,1.010000e-08,47.0,3.538278,3.818930,4.032463,3.80
4,4,QIPENSTSSQADDEWCYVLI,0,5.148098,10.131437,11.838327,12.629829,12.705135,91,1759,...,1.0,10.0,552.0,561.0,1.400000e+00,23.5,3.460374,3.833635,4.114419,3.80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
415,422,ASQGSDDDWDDEWDDSSTVADEPGALGSGAYPDLDG,0,6.093138,7.077381,7.625063,7.758434,6.743610,28,1042,...,1.0,36.0,146.0,181.0,1.450000e-17,72.4,1.663313,1.808750,1.617183,1.70
416,423,LEATGPGGSQAINNLRRSNSTTQVSQPRSGSPRPTE,0,6.929649,7.823032,8.205766,7.752720,6.165534,11,731,...,1.0,36.0,59.0,94.0,3.150000e-18,74.3,1.910997,1.806375,1.375032,1.70
417,424,MPNTSVVLDTDAEFVILLLFLLLLFFFFRASFA,0,4.431676,7.914457,8.140802,7.387363,6.622837,407,4788,...,1.0,15.0,642.0,656.0,1.750000e-04,35.4,1.883288,1.654507,1.566592,1.70
418,425,MSQAVQQRYSTIKQNMGTQFI,0,3.409332,7.021036,7.790198,7.932998,6.418514,48,278,...,NaN,NaN,NaN,NaN,NaN,NaN,1.733747,1.881311,1.481003,1.70
419,426,RVVNGAFMVLKGHRSIVNQARFNPHTYMICSLV,0,5.037973,6.692744,7.307211,7.830723,7.013530,11,197,...,1.0,31.0,320.0,350.0,4.730000e-17,70.9,1.527741,1.838798,1.730251,1.70

In [18]:
# This means: 1 amino acid from F/W/Y, followed by any 3, then 1 from L/V/I
pattern = r'[FWY]..[LVIFWY]'

# Filter rows where 'ID' matches the motif
matching_df = df[df['ID'].str.contains(pattern, regex=True)]

In [19]:
matching_df

,Unnamed: 0,ID,ER 0,ER 1,ER 3,ER 4,ER 5,ER 6,Input Count,1 Count,...,Query start,Query End,Hit Start,Hit End,E-value,Score (Bits),z_score_4,z_score_5,z_score_6,avg_z_score
0,0,DIDNFDIDDFDDDDDWEDICII,0,4.094998,9.506665,12.105609,13.229315,14.031836,976,9092,...,5.0,19.0,256.0,270.0,1.900000e+00,23.1,3.574377,4.082822,4.670163,4.11
1,1,LWQPHSSKQDDMWEHIAISML,0,4.420856,9.955033,12.104137,12.854852,13.584948,244,2849,...,1.0,17.0,465.0,481.0,4.550000e-07,42.0,3.573749,3.927170,4.482965,3.99
2,2,VIEEADLDGDGSWALLTSRT,0,6.061220,10.521183,11.960512,12.786388,12.782009,10,364,...,1.0,11.0,152.0,162.0,7.100000e-02,27.3,3.512489,3.898712,4.146620,3.85
3,3,LHNPESGEEAVALLEELQRDLGWDILA,0,5.191722,10.334677,12.020974,12.594453,12.509488,13,259,...,1.0,21.0,117.0,137.0,1.010000e-08,47.0,3.538278,3.818930,4.032463,3.80
4,4,QIPENSTSSQADDEWCYVLI,0,5.148098,10.131437,11.838327,12.629829,12.705135,91,1759,...,1.0,10.0,552.0,561.0,1.400000e+00,23.5,3.460374,3.833635,4.114419,3.80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
413,420,HLAAGYNNLEVAEYLLEHGADVNAQTRVV,0,4.039740,7.065926,7.296732,7.828102,7.030019,29,260,...,1.0,27.0,842.0,868.0,3.130000e-11,54.3,1.523272,1.837709,1.737157,1.70
415,422,ASQGSDDDWDDEWDDSSTVADEPGALGSGAYPDLDG,0,6.093138,7.077381,7.625063,7.758434,6.743610,28,1042,...,1.0,36.0,146.0,181.0,1.450000e-17,72.4,1.663313,1.808750,1.617183,1.70
417,424,MPNTSVVLDTDAEFVILLLFLLLLFFFFRASFA,0,4.431676,7.914457,8.140802,7.387363,6.622837,407,4788,...,1.0,15.0,642.0,656.0,1.750000e-04,35.4,1.883288,1.654507,1.566592,1.70
418,425,MSQAVQQRYSTIKQNMGTQFI,0,3.409332,7.021036,7.790198,7.932998,6.418514,48,278,...,NaN,NaN,NaN,NaN,NaN,NaN,1.733747,1.881311,1.481003,1.70
419,426,RVVNGAFMVLKGHRSIVNQARFNPHTYMICSLV,0,5.037973,6.692744,7.307211,7.830723,7.013530,11,197,...,1.0,31.0,320.0,350.0,4.730000e-17,70.9,1.527741,1.838798,1.730251,1.70

In [14]:
df_jh = pd.read_csv("/Users/jenniferkosmatka/Downloads/09_binders_from_Jackson.csv", sep=",")

In [27]:
df_jh

                                       ID  Input Count  avg_z_score     7mer
0                  DIDNFDIDDFDDDDDWEDICII          976         4.11  DDDWEDI
1                   LWQPHSSKQDDMWEHIAISML          244         3.99  DDMWEHI
2                    VIEEADLDGDGSWALLTSRT           10         3.85  DGSWALL
3             LHNPESGEEAVALLEELQRDLGWDILA           13         3.80  DLGWDIL
4                    QIPENSTSSQADDEWCYVLI           91         3.80  DDEWCYV
..                                    ...          ...          ...      ...
268     MPNTSVVLDTDAEFVILLLFLLLLFFFFRASFA          407         1.70  LLLFFFF
269         HLAAGYNNLEVAEYLLEHGADVNAQTRVV           29         1.70  AAGYNNL
270  ASQGSDDDWDDEWDDSSTVADEPGALGSGAYPDLDG           28         1.70  SGAYPDL
271                 MSQAVQQRYSTIKQNMGTQFI           48         1.70  QQRYSTI
272     RVVNGAFMVLKGHRSIVNQARFNPHTYMICSLV           11         1.70  NGAFMVL

[273 rows x 4 columns]

In [16]:
df_jk = pd.read_csv("/Users/jenniferkosmatka/Downloads/09_binders_from_Jen.csv", sep=",")

In [17]:
df_jk

                                    ID  Input Count  avg_z_score     7mer
0               DIDNFDIDDFDDDDDWEDICII          976         4.11  DDDWEDI
1                LWQPHSSKQDDMWEHIAISML          244         3.99  DDMWEHI
2                 VIEEADLDGDGSWALLTSRT           10         3.85  DGSWALL
3          LHNPESGEEAVALLEELQRDLGWDILA           13         3.80  DLGWDIL
4                 QIPENSTSSQADDEWCYVLI           91         3.80  DDEWCYV
..                                 ...          ...          ...      ...
292  MPNTSVVLDTDAEFVILLLFLLLLFFFFRASFA          407         1.70  LLLFLLL
293  MPNTSVVLDTDAEFVILLLFLLLLFFFFRASFA          407         1.70  LLLFFFF
294      HLAAGYNNLEVAEYLLEHGADVNAQTRVV           29         1.70  AAGYNNL
295  RVVNGAFMVLKGHRSIVNQARFNPHTYMICSLV           11         1.70  NGAFMVL
296              MSQAVQQRYSTIKQNMGTQFI           48         1.70  QQRYSTI

[297 rows x 4 columns]

In [20]:
# This means: 1 amino acid from F/W/Y, followed by any 3, then 1 from L/V/I
pattern = r'[FWY]..[LVIFWY]'

# Filter rows where 'ID' matches the motif
matching_df_jk = df_jk[df_jk['ID'].str.contains(pattern, regex=True)]

In [21]:
matching_df_jk

                                    ID  Input Count  avg_z_score     7mer
0               DIDNFDIDDFDDDDDWEDICII          976         4.11  DDDWEDI
1                LWQPHSSKQDDMWEHIAISML          244         3.99  DDMWEHI
2                 VIEEADLDGDGSWALLTSRT           10         3.85  DGSWALL
3          LHNPESGEEAVALLEELQRDLGWDILA           13         3.80  DLGWDIL
4                 QIPENSTSSQADDEWCYVLI           91         3.80  DDEWCYV
..                                 ...          ...          ...      ...
292  MPNTSVVLDTDAEFVILLLFLLLLFFFFRASFA          407         1.70  LLLFLLL
293  MPNTSVVLDTDAEFVILLLFLLLLFFFFRASFA          407         1.70  LLLFFFF
294      HLAAGYNNLEVAEYLLEHGADVNAQTRVV           29         1.70  AAGYNNL
295  RVVNGAFMVLKGHRSIVNQARFNPHTYMICSLV           11         1.70  NGAFMVL
296              MSQAVQQRYSTIKQNMGTQFI           48         1.70  QQRYSTI

[297 rows x 4 columns]

In [28]:
df_postprocess = pd.read_csv('/Users/jenniferkosmatka/MIT Dropbox/jhdavislab/06_davis_lab_papers/in_preparation/03_lc3bscreen_jk/supporting data/SF3_input_postcollapse_JK.csv')

In [29]:
df_postprocess

,Unnamed: 0,ID,ER 0_x,ER 1_x,ER 3_x,ER 4_x,ER 5_x,ER 6_x,Cluster Id_x,Input Count_x,...,Query start_x,Query End_x,Hit Start_x,Hit End_x,E-value_x,Score (Bits)_x,z_score_4,z_score_5,z_score_6,avg_z_score
0,229422,DIDNFDIDDFDDDDDWEDICII,0,4.094998,9.506665,12.105609,13.229315,14.031836,229609,976,...,5.0,19.0,256.0,270.0,1.900000e+00,23.1,3.574377,4.082822,4.670163,4.11
1,683178,LWQPHSSKQDDMWEHIAISML,0,4.420856,9.955033,12.104137,12.854852,13.584948,683868,244,...,1.0,17.0,465.0,481.0,4.550000e-07,42.0,3.573749,3.927170,4.482965,3.99
2,426137,VIEEADLDGDGSWALLTSRT,0,6.061220,10.521183,11.960512,12.786388,12.782009,426523,10,...,1.0,11.0,152.0,162.0,7.100000e-02,27.3,3.512489,3.898712,4.146620,3.85
3,480519,LHNPESGEEAVALLEELQRDLGWDILA,0,5.191722,10.334677,12.020974,12.594453,12.509488,480943,13,...,1.0,21.0,117.0,137.0,1.010000e-08,47.0,3.538278,3.818930,4.032463,3.80
4,810153,QIPENSTSSQADDEWCYVLI,0,5.148098,10.131437,11.838327,12.629829,12.705135,810989,91,...,1.0,10.0,552.0,561.0,1.400000e+00,23.5,3.460374,3.833635,4.114419,3.80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
968944,968944,YWKLTIMSFIKLMVVNPSILIVSFMVMKLPKMCMK,0,NaN,NaN,NaN,NaN,NaN,969981,9,...,6.0,35.0,279.0,308.0,8.800000e+00,22.3,NaN,NaN,NaN,NaN
968945,968945,YWKNLPVCKPCPAASFLLCTEY,0,NaN,NaN,NaN,NaN,NaN,969982,1,...,6.0,16.0,445.0,455.0,6.300000e+00,21.9,NaN,NaN,NaN,NaN
968946,968946,YWKYGEAASTECNSVCFGDHTQPCGGDGRIILFDTL,0,NaN,NaN,NaN,NaN,NaN,969983,34,...,1.0,36.0,175.0,210.0,8.050000e-21,81.6,NaN,NaN,NaN,NaN
968947,968947,YWKYGEAASTACNSVCFGGSHPTVWWRWPYHPL,0,NaN,NaN,NaN,NaN,NaN,969984,11,...,1.0,18.0,175.0,192.0,4.000000e-06,40.0,NaN,NaN,NaN,NaN
968948,968948,YWKYGEAAVPNATASASGITPNRVVAMAVSSSLIL,0,NaN,NaN,NaN,NaN,NaN,969985,1,...,4.0,35.0,657.0,688.0,1.900000e-01,26.9,NaN,NaN,NaN,NaN

In [31]:
df2 = df_postprocess[df_postprocess['Input Count_x']>=10]

In [32]:
df2

,Unnamed: 0,ID,ER 0_x,ER 1_x,ER 3_x,ER 4_x,ER 5_x,ER 6_x,Cluster Id_x,Input Count_x,...,Query start_x,Query End_x,Hit Start_x,Hit End_x,E-value_x,Score (Bits)_x,z_score_4,z_score_5,z_score_6,avg_z_score
0,229422,DIDNFDIDDFDDDDDWEDICII,0,4.094998,9.506665,12.105609,13.229315,14.031836,229609,976,...,5.0,19.0,256.0,270.0,1.900000e+00,23.1,3.574377,4.082822,4.670163,4.11
1,683178,LWQPHSSKQDDMWEHIAISML,0,4.420856,9.955033,12.104137,12.854852,13.584948,683868,244,...,1.0,17.0,465.0,481.0,4.550000e-07,42.0,3.573749,3.927170,4.482965,3.99
2,426137,VIEEADLDGDGSWALLTSRT,0,6.061220,10.521183,11.960512,12.786388,12.782009,426523,10,...,1.0,11.0,152.0,162.0,7.100000e-02,27.3,3.512489,3.898712,4.146620,3.85
3,480519,LHNPESGEEAVALLEELQRDLGWDILA,0,5.191722,10.334677,12.020974,12.594453,12.509488,480943,13,...,1.0,21.0,117.0,137.0,1.010000e-08,47.0,3.538278,3.818930,4.032463,3.80
4,810153,QIPENSTSSQADDEWCYVLI,0,5.148098,10.131437,11.838327,12.629829,12.705135,810989,91,...,1.0,10.0,552.0,561.0,1.400000e+00,23.5,3.460374,3.833635,4.114419,3.80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
968935,968935,YWITIDNPYVVAWHGYATGRLAPGIRGSPRLGYLVA,0,3.249749,NaN,NaN,NaN,NaN,969972,27,...,1.0,36.0,233.0,268.0,1.710000e-19,78.2,NaN,NaN,NaN,NaN
968939,968939,YWKESDKLLLIGLPAEEVPLPRLRNMIENVIQTLKF,0,2.764096,1.467049,-0.573207,NaN,NaN,969976,64,...,1.0,36.0,378.0,413.0,3.010000e-19,77.4,NaN,NaN,NaN,NaN
968940,968940,YWKNESGTWIQYGEEKDKRKNSNVDSSYLESLYQSC,0,0.565013,NaN,NaN,NaN,NaN,969977,31,...,1.0,36.0,610.0,645.0,8.820000e-20,79.0,NaN,NaN,NaN,NaN
968946,968946,YWKYGEAASTECNSVCFGDHTQPCGGDGRIILFDTL,0,NaN,NaN,NaN,NaN,NaN,969983,34,...,1.0,36.0,175.0,210.0,8.050000e-21,81.6,NaN,NaN,NaN,NaN
968947,968947,YWKYGEAASTACNSVCFGGSHPTVWWRWPYHPL,0,NaN,NaN,NaN,NaN,NaN,969984,11,...,1.0,18.0,175.0,192.0,4.000000e-06,40.0,NaN,NaN,NaN,NaN

In [33]:
df3 = df2[df2['avg_z_score']>=1.70]

In [34]:
df3

,Unnamed: 0,ID,ER 0_x,ER 1_x,ER 3_x,ER 4_x,ER 5_x,ER 6_x,Cluster Id_x,Input Count_x,...,Query start_x,Query End_x,Hit Start_x,Hit End_x,E-value_x,Score (Bits)_x,z_score_4,z_score_5,z_score_6,avg_z_score
0,229422,DIDNFDIDDFDDDDDWEDICII,0,4.094998,9.506665,12.105609,13.229315,14.031836,229609,976,...,5.0,19.0,256.0,270.0,1.900000e+00,23.1,3.574377,4.082822,4.670163,4.11
1,683178,LWQPHSSKQDDMWEHIAISML,0,4.420856,9.955033,12.104137,12.854852,13.584948,683868,244,...,1.0,17.0,465.0,481.0,4.550000e-07,42.0,3.573749,3.927170,4.482965,3.99
2,426137,VIEEADLDGDGSWALLTSRT,0,6.061220,10.521183,11.960512,12.786388,12.782009,426523,10,...,1.0,11.0,152.0,162.0,7.100000e-02,27.3,3.512489,3.898712,4.146620,3.85
3,480519,LHNPESGEEAVALLEELQRDLGWDILA,0,5.191722,10.334677,12.020974,12.594453,12.509488,480943,13,...,1.0,21.0,117.0,137.0,1.010000e-08,47.0,3.538278,3.818930,4.032463,3.80
4,810153,QIPENSTSSQADDEWCYVLI,0,5.148098,10.131437,11.838327,12.629829,12.705135,810989,91,...,1.0,10.0,552.0,561.0,1.400000e+00,23.5,3.460374,3.833635,4.114419,3.80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
422,136623,ASQGSDDDWDDEWDDSSTVADEPGALGSGAYPDLDG,0,6.093138,7.077381,7.625063,7.758434,6.743610,136733,28,...,1.0,36.0,146.0,181.0,1.450000e-17,72.4,1.663313,1.808750,1.617183,1.70
423,608085,LEATGPGGSQAINNLRRSNSTTQVSQPRSGSPRPTE,0,6.929649,7.823032,8.205766,7.752720,6.165534,608664,11,...,1.0,36.0,59.0,94.0,3.150000e-18,74.3,1.910997,1.806375,1.375032,1.70
424,654755,MPNTSVVLDTDAEFVILLLFLLLLFFFFRASFA,0,4.431676,7.914457,8.140802,7.387363,6.622837,655397,407,...,1.0,15.0,642.0,656.0,1.750000e-04,35.4,1.883288,1.654507,1.566592,1.70
425,723996,MSQAVQQRYSTIKQNMGTQFI,0,3.409332,7.021036,7.790198,7.932998,6.418514,724743,48,...,NaN,NaN,NaN,NaN,NaN,NaN,1.733747,1.881311,1.481003,1.70
426,861200,RVVNGAFMVLKGHRSIVNQARFNPHTYMICSLV,0,5.037973,6.692744,7.307211,7.830723,7.013530,862092,11,...,1.0,31.0,320.0,350.0,4.730000e-17,70.9,1.527741,1.838798,1.730251,1.70

In [37]:
pattern = r'HPQ'

# Filter rows where 'ID' matches the motif
df4 = df3[~df3['ID'].str.contains(pattern, regex=True)]

In [36]:
df4

,Unnamed: 0,ID,ER 0_x,ER 1_x,ER 3_x,ER 4_x,ER 5_x,ER 6_x,Cluster Id_x,Input Count_x,...,Query start_x,Query End_x,Hit Start_x,Hit End_x,E-value_x,Score (Bits)_x,z_score_4,z_score_5,z_score_6,avg_z_score
0,229422,DIDNFDIDDFDDDDDWEDICII,0,4.094998,9.506665,12.105609,13.229315,14.031836,229609,976,...,5.0,19.0,256.0,270.0,1.900000e+00,23.1,3.574377,4.082822,4.670163,4.11
1,683178,LWQPHSSKQDDMWEHIAISML,0,4.420856,9.955033,12.104137,12.854852,13.584948,683868,244,...,1.0,17.0,465.0,481.0,4.550000e-07,42.0,3.573749,3.927170,4.482965,3.99
2,426137,VIEEADLDGDGSWALLTSRT,0,6.061220,10.521183,11.960512,12.786388,12.782009,426523,10,...,1.0,11.0,152.0,162.0,7.100000e-02,27.3,3.512489,3.898712,4.146620,3.85
3,480519,LHNPESGEEAVALLEELQRDLGWDILA,0,5.191722,10.334677,12.020974,12.594453,12.509488,480943,13,...,1.0,21.0,117.0,137.0,1.010000e-08,47.0,3.538278,3.818930,4.032463,3.80
4,810153,QIPENSTSSQADDEWCYVLI,0,5.148098,10.131437,11.838327,12.629829,12.705135,810989,91,...,1.0,10.0,552.0,561.0,1.400000e+00,23.5,3.460374,3.833635,4.114419,3.80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
422,136623,ASQGSDDDWDDEWDDSSTVADEPGALGSGAYPDLDG,0,6.093138,7.077381,7.625063,7.758434,6.743610,136733,28,...,1.0,36.0,146.0,181.0,1.450000e-17,72.4,1.663313,1.808750,1.617183,1.70
423,608085,LEATGPGGSQAINNLRRSNSTTQVSQPRSGSPRPTE,0,6.929649,7.823032,8.205766,7.752720,6.165534,608664,11,...,1.0,36.0,59.0,94.0,3.150000e-18,74.3,1.910997,1.806375,1.375032,1.70
424,654755,MPNTSVVLDTDAEFVILLLFLLLLFFFFRASFA,0,4.431676,7.914457,8.140802,7.387363,6.622837,655397,407,...,1.0,15.0,642.0,656.0,1.750000e-04,35.4,1.883288,1.654507,1.566592,1.70
425,723996,MSQAVQQRYSTIKQNMGTQFI,0,3.409332,7.021036,7.790198,7.932998,6.418514,724743,48,...,NaN,NaN,NaN,NaN,NaN,NaN,1.733747,1.881311,1.481003,1.70
426,861200,RVVNGAFMVLKGHRSIVNQARFNPHTYMICSLV,0,5.037973,6.692744,7.307211,7.830723,7.013530,862092,11,...,1.0,31.0,320.0,350.0,4.730000e-17,70.9,1.527741,1.838798,1.730251,1.70

In [42]:
pattern = r'[FWY]..[LVIFWY]'
df4['motif_matches'] = df4['ID'].str.findall(pattern)
df_filtered = df4[df4['motif_matches'].apply(lambda x: len(x) > 0)]

/var/folders/2c/6s7hc_xd4wj4sty6v7mf05n00000gn/T/ipykernel_55974/1222453732.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df4['motif_matches'] = df4['ID'].str.findall(pattern)

In [43]:
df_filtered

,Unnamed: 0,ID,ER 0_x,ER 1_x,ER 3_x,ER 4_x,ER 5_x,ER 6_x,Cluster Id_x,Input Count_x,...,Query End_x,Hit Start_x,Hit End_x,E-value_x,Score (Bits)_x,z_score_4,z_score_5,z_score_6,avg_z_score,motif_matches
0,229422,DIDNFDIDDFDDDDDWEDICII,0,4.094998,9.506665,12.105609,13.229315,14.031836,229609,976,...,19.0,256.0,270.0,1.900000e+00,23.1,3.574377,4.082822,4.670163,4.11,[WEDI]
1,683178,LWQPHSSKQDDMWEHIAISML,0,4.420856,9.955033,12.104137,12.854852,13.584948,683868,244,...,17.0,465.0,481.0,4.550000e-07,42.0,3.573749,3.927170,4.482965,3.99,[WEHI]
2,426137,VIEEADLDGDGSWALLTSRT,0,6.061220,10.521183,11.960512,12.786388,12.782009,426523,10,...,11.0,152.0,162.0,7.100000e-02,27.3,3.512489,3.898712,4.146620,3.85,[WALL]
3,480519,LHNPESGEEAVALLEELQRDLGWDILA,0,5.191722,10.334677,12.020974,12.594453,12.509488,480943,13,...,21.0,117.0,137.0,1.010000e-08,47.0,3.538278,3.818930,4.032463,3.80,[WDIL]
4,810153,QIPENSTSSQADDEWCYVLI,0,5.148098,10.131437,11.838327,12.629829,12.705135,810989,91,...,10.0,552.0,561.0,1.400000e+00,23.5,3.460374,3.833635,4.114419,3.80,[WCYV]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
420,102392,HLAAGYNNLEVAEYLLEHGADVNAQTRVV,0,4.039740,7.065926,7.296732,7.828102,7.030019,102470,29,...,27.0,842.0,868.0,3.130000e-11,54.3,1.523272,1.837709,1.737157,1.70,[YNNL]
422,136623,ASQGSDDDWDDEWDDSSTVADEPGALGSGAYPDLDG,0,6.093138,7.077381,7.625063,7.758434,6.743610,136733,28,...,36.0,146.0,181.0,1.450000e-17,72.4,1.663313,1.808750,1.617183,1.70,[YPDL]
424,654755,MPNTSVVLDTDAEFVILLLFLLLLFFFFRASFA,0,4.431676,7.914457,8.140802,7.387363,6.622837,655397,407,...,15.0,642.0,656.0,1.750000e-04,35.4,1.883288,1.654507,1.566592,1.70,"[FVIL, FLLL, FFFF]"
425,723996,MSQAVQQRYSTIKQNMGTQFI,0,3.409332,7.021036,7.790198,7.932998,6.418514,724743,48,...,NaN,NaN,NaN,NaN,NaN,1.733747,1.881311,1.481003,1.70,[YSTI]
426,861200,RVVNGAFMVLKGHRSIVNQARFNPHTYMICSLV,0,5.037973,6.692744,7.307211,7.830723,7.013530,862092,11,...,31.0,320.0,350.0,4.730000e-17,70.9,1.527741,1.838798,1.730251,1.70,[FMVL]

In [44]:
df_exploded = df_filtered.explode('motif_matches').reset_index(drop=True)

In [45]:
df_exploded

,Unnamed: 0,ID,ER 0_x,ER 1_x,ER 3_x,ER 4_x,ER 5_x,ER 6_x,Cluster Id_x,Input Count_x,...,Query End_x,Hit Start_x,Hit End_x,E-value_x,Score (Bits)_x,z_score_4,z_score_5,z_score_6,avg_z_score,motif_matches
0,229422,DIDNFDIDDFDDDDDWEDICII,0,4.094998,9.506665,12.105609,13.229315,14.031836,229609,976,...,19.0,256.0,270.0,1.900000e+00,23.1,3.574377,4.082822,4.670163,4.11,WEDI
1,683178,LWQPHSSKQDDMWEHIAISML,0,4.420856,9.955033,12.104137,12.854852,13.584948,683868,244,...,17.0,465.0,481.0,4.550000e-07,42.0,3.573749,3.927170,4.482965,3.99,WEHI
2,426137,VIEEADLDGDGSWALLTSRT,0,6.061220,10.521183,11.960512,12.786388,12.782009,426523,10,...,11.0,152.0,162.0,7.100000e-02,27.3,3.512489,3.898712,4.146620,3.85,WALL
3,480519,LHNPESGEEAVALLEELQRDLGWDILA,0,5.191722,10.334677,12.020974,12.594453,12.509488,480943,13,...,21.0,117.0,137.0,1.010000e-08,47.0,3.538278,3.818930,4.032463,3.80,WDIL
4,810153,QIPENSTSSQADDEWCYVLI,0,5.148098,10.131437,11.838327,12.629829,12.705135,810989,91,...,10.0,552.0,561.0,1.400000e+00,23.5,3.460374,3.833635,4.114419,3.80,WCYV
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
302,654755,MPNTSVVLDTDAEFVILLLFLLLLFFFFRASFA,0,4.431676,7.914457,8.140802,7.387363,6.622837,655397,407,...,15.0,642.0,656.0,1.750000e-04,35.4,1.883288,1.654507,1.566592,1.70,FVIL
303,654755,MPNTSVVLDTDAEFVILLLFLLLLFFFFRASFA,0,4.431676,7.914457,8.140802,7.387363,6.622837,655397,407,...,15.0,642.0,656.0,1.750000e-04,35.4,1.883288,1.654507,1.566592,1.70,FLLL
304,654755,MPNTSVVLDTDAEFVILLLFLLLLFFFFRASFA,0,4.431676,7.914457,8.140802,7.387363,6.622837,655397,407,...,15.0,642.0,656.0,1.750000e-04,35.4,1.883288,1.654507,1.566592,1.70,FFFF
305,723996,MSQAVQQRYSTIKQNMGTQFI,0,3.409332,7.021036,7.790198,7.932998,6.418514,724743,48,...,NaN,NaN,NaN,NaN,NaN,1.733747,1.881311,1.481003,1.70,YSTI
306,861200,RVVNGAFMVLKGHRSIVNQARFNPHTYMICSLV,0,5.037973,6.692744,7.307211,7.830723,7.013530,862092,11,...,31.0,320.0,350.0,4.730000e-17,70.9,1.527741,1.838798,1.730251,1.70,FMVL